import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('favorites container workbench UI', () => {
  it('renders compact containers, reviewed path rows, on-demand directory tools, and row-local actions', () => {
    const page = readFileSync(resolve(process.cwd(), 'src/pages/FavoritesPage.vue'), 'utf8')
    const tree = readFileSync(resolve(process.cwd(), 'src/components/FavoriteTree.vue'), 'utf8')
    const app = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')

    expect(page).toContain('favoriteContainerRows')
    expect(page).toContain('favorite-path-list')
    expect(page).toContain('favorite-virtual-section')
    expect(page).toContain('favorite-directory-section')
    expect(page).toContain('favorite-advanced-panel')
    expect(page).not.toContain('favorite-focus-actions')
    expect(page).toContain('function dispatchFavoriteRowAction')
    expect(page).toContain('function dispatchDirectoryRowAction')
    expect(page).toContain('favorite-row-actions')
    expect(page).toContain('favorite-action-drawer')
    expect(page).toContain('favorite-pick-review')
    expect(page).toContain('favorite-path-picker')
    expect(page).toContain(':nodes="props.snapshot.state.favorites"')
    expect(page).toContain("emit('dispatch', 'favorites.draft.pickPath', { kind: 'file' })")
    expect(page).toContain("emit('dispatch', 'favorites.draft.pickPath', { kind: 'folder' })")
    expect(page).toContain("emit('dispatch', 'favorites.directory.addSelected')")
    expect(page).toContain("emit('updatePickReviewItem'")
    expect(page).toContain('@contextmenu.prevent="openFavoriteContextMenu')
    expect(page).toContain('@contextmenu.prevent="openDirectoryContextMenu')
    expect(tree).toContain('@contextmenu.prevent')
    expect(tree).toContain('action: [id: string, actionId: string]')
    expect(tree).toContain('tree-row-actions')
    expect(tree).toContain("@click.stop=\"emit('action', row.node.id, 'favorites.drawer.open')\"")
    expect(tree).toContain('favoriteTreeMoveTarget')
    expect(tree).toContain("return 'before'")
    expect(tree).toContain("return 'inside'")
    expect(tree).toContain("return 'after'")
    expect(app).toContain('@focus-directory="runtime.focusFavoriteDirectory"')
    expect(app).toContain('@toggle-directory="runtime.toggleFavoriteDirectorySelection"')
    expect(app).toContain('@update-pick-review-item="runtime.updateFavoritePickReviewItem"')
    expect(css).toContain('.favorite-row-actions')
    expect(css).toContain('.tree-row-actions')
  })
})
