import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('mqtt page layout', () => {
  it('is lazy-loaded and exposes compact MQTT workbench surfaces', () => {
    const app = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')
    const page = readFileSync(resolve(process.cwd(), 'src/pages/MqttPage.vue'), 'utf8')
    const publishRecordList = readFileSync(resolve(process.cwd(), 'src/components/MqttPublishRecordList.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')
    const functionSource = (name: string) => {
      const start = page.indexOf(`function ${name}`)
      const end = page.indexOf('\n}\n\nfunction ', start)
      return page.slice(start, end === -1 ? undefined : end + 3)
    }

    expect(app).toContain("defineAsyncComponent(() => import('./pages/MqttPage.vue'))")
    expect(app).toContain('<template #mqtt>')
    expect(page).toContain('class="mqtt-workbench-grid"')
    expect(page).toContain('mqtt-connection-rail')
    expect(page).toContain('mqtt-subscription-rail')
    expect(page).toContain('mqtt-message-workspace')
    expect(page).toContain('mqtt-workspace-split')
    expect(page).toContain('mqtt-panel-toggle')
    expect(page).toContain('mqtt.subscription.panel.toggle')
    expect(page).toContain('mqtt.layout.toggle')
    expect(page).toContain('mqtt.connection.connect')
    expect(page).toContain('data-role="mqtt-connections"')
    expect(page).toContain('@contextmenu.prevent="openConnectionMenu(config)"')
    expect(page).toContain('mqtt.connection.toggleSelect')
    expect(page).toContain('mqttSelectedConfigIds')
    const connectionActionStart = page.indexOf('<div class="mqtt-config-actions">')
    const connectionActionEnd = page.indexOf('</div>', connectionActionStart)
    const connectionActions = page.slice(connectionActionStart, connectionActionEnd)
    expect(connectionActions.match(/<button/g)).toHaveLength(3)
    expect(connectionActions).toContain('mqtt.connection.connect')
    expect(connectionActions).toContain('mqtt.connection.disconnect')
    expect(connectionActions).toContain('mqtt.drawer.open')
    expect(connectionActions).not.toContain('mqtt.config.edit')
    expect(connectionActions).not.toContain('mqtt.log.drawer.open')
    expect(connectionActions).not.toContain('mqtt.connection.copyAddress')
    expect(connectionActions).not.toContain('mqtt.detail.open')
    expect(page).toContain('mqtt.publish.send')
    expect(page).toContain('mqtt.record.resendDraft')
    expect(page).toContain('autoReconnect')
    expect(page).toContain('reconnectPeriodMs')
    expect(page).toContain('connectTimeoutMs')
    expect(page).toContain('keepaliveSec')
    expect(page).toContain('syncRecords')
    expect(page).toContain('服务器地址')
    expect(page).toContain('data-mqtt-field="host"')
    expect(page).toContain('data-mqtt-field="port"')
    expect(page).toContain('data-mqtt-field="path"')
    expect(page).toContain('refreshConfigClientId')
    expect(page).toContain('aria-label="随机刷新 Client ID"')
    expect(page).toContain('mqtt-client-id-row')
    expect(page).toContain('mqtt-endpoint-compact-row')
    expect(page).toContain('mqtt-config-drawer')
    expect(page).toContain('mqtt-config-drawer-overlay')
    expect(page).toContain('addConfigSubscriptionItem')
    expect(page).toContain('updateConfigSubscriptionItem')
    expect(page).toContain('addConfigPublishTopic')
    expect(page).toContain('updateConfigPublishTopic')
    expect(page).toContain('data-mqtt-field="subscriptions"')
    expect(page).toContain('configSubscriptionRowFocused(index)')
    expect(page).toContain('configPublishRowFocused(index)')
    expect(page).toContain('placeholder="订阅别名"')
    expect(page).toContain('placeholder="plc/+/status"')
    expect(page).toContain('role="dialog"')
    expect(page).toContain('aria-modal="true"')
    expect(page).not.toContain('<section v-if="props.snapshot.mqttConfigDraft" class="mqtt-config-editor"')
    expect(page).not.toContain('<section v-else class="mqtt-workspace-body">')
    expect(page).toContain('SSL/TLS')
    expect(page).not.toContain('当前连接地址')
    expect(page).not.toContain('mqtt-endpoint-preview')
    expect(page).toContain('mqtt-log-drawer')
    expect(page).toContain('focusLog')
    expect(page).toContain('mqtt.log.clearAll')
    expect(page).toContain('mqtt.log.clearCurrentConfig')
    expect(page).toContain('mqtt.log.delete')
    expect(page).toContain('日志详情')
    expect(page).toContain('清空本连接')
    expect(page).toContain('清空全部')
    expect(page).toContain('错误日志')
    expect(page).toContain('订阅')
    expect(page).toContain('添加订阅')
    expect(page).toContain('mqtt-subscription-list')
    expect(page).not.toContain('class="mqtt-icon-button mqtt-subscription-delete"')
    expect(page).toContain('mqtt.subscription.toggleSelect')
    expect(page).toContain('mqtt.subscription.applyFilter')
    expect(page).toContain('mqtt.subscription.copyTopic')
    expect(page).toContain('mqtt.subscription.useAsPublishTopic')
    expect(page).toContain('@contextmenu.prevent="openSubscriptionMenu(row.topic)"')
    expect(page).toContain('mqtt.subscription.deleteSelected')
    expect(page).toContain('mqtt.subscription.clearAll')
    expect(page).toContain('class="drawer-action mqtt-drawer-action"')
    expect(page).toContain('class="drawer-action-icon mqtt-drawer-action-icon"')
    expect(page).toContain('class="drawer-action-copy"')
    expect(page).toContain('role="menuitem"')
    expect(page).toContain('mqttSubscriptionDraft')
    expect(page).not.toContain('data-role="mqtt-favorite-editor"')
    expect(page).toContain('mqtt-subscription-modal')
    expect(page).toContain('mqtt-subscription-editor-row')
    expect(page).toContain('mqtt.subscription.editor.open')
    expect(page).not.toContain(':disabled="!activeConfig" title="管理订阅"')
    expect(page).toContain('mqtt.subscription.editor.save')
    expect(page).toContain('mqtt.subscription.editor.cancel')
    expect(page).toContain('mqtt.subscription.editor.nextRow')
    expect(page).toContain('mqtt.subscription.editor.prevRow')
    expect(page).toContain('mqtt.subscription.editor.deleteRow')
    expect(page).toContain('data-role="mqtt-subscription-editor"')
    expect(page).toContain('data-mqtt-subscription-item-id')
    expect(page).toContain('activeItemId')
    expect(page).not.toContain('document.querySelector<HTMLInputElement>(`[data-mqtt-subscription-field="${field}"]`)')
    expect(page).not.toContain('watch(() => [props.snapshot.mqttSubscriptionDraft?.activeItemId, props.snapshot.mqttSubscriptionDraft?.activeField] as const')
    expect(page).toContain('const alreadyFocused = document.activeElement === input')
    expect(page).toContain('if (!alreadyFocused) input?.setSelectionRange(input.value.length, input.value.length)')
    expect(page).not.toContain("topic: '#'")
    expect(page).toContain(':key="item.id"')
    expect(page).not.toContain(':key="`${index}:${item.topic}`"')
    expect(page).toContain('订阅管理')
    expect(page).toContain('订阅别名')
    expect(page).toContain('mqtt-config-subscription-list')
    expect(page).toContain('mqtt-config-subscription-row')
    expect(page).toContain('data-role="mqtt-config-subscription-editor"')
    expect(page).toContain('data-mqtt-config-subscription-index')
    expect(page).toContain('data-mqtt-config-subscription-field="topic"')
    expect(page).toContain('mqtt.config.subscription.focus')
    expect(page).toContain('mqtt.config.subscription.deleteRow')
    expect(page).not.toContain('<span>QoS {{ configForm.qos }}</span>')
    expect(page).toContain('mqtt-config-publish-list')
    expect(page).toContain('mqtt-config-publish-row')
    expect(page).toContain('data-role="mqtt-config-publish-editor"')
    expect(page).toContain('data-mqtt-config-publish-index')
    expect(page).toContain('data-mqtt-config-publish-field="topic"')
    expect(page).toContain('mqtt.config.publish.focus')
    expect(page).toContain('mqtt.config.publish.deleteRow')
    expect(page).toContain('默认发布')
    expect(page).toContain('mqtt-config-options-panel')
    expect(page).toContain('mqtt-config-checkbox-grid')
    expect(page).toContain('暂无订阅 topic，可在这里添加')
    expect(page).not.toContain('title="管理订阅"')
    expect(page).toContain('mqtt-subscription-unread')
    expect(page).toContain('mqtt.subscription.select')
    expect(page).toContain(':data-quick-jump-label="row.displayName"')
    expect(page).toContain(':data-quick-jump-search="row.topic"')
    expect(page).toContain('<strong data-quick-jump-anchor>{{ row.displayName }}</strong>')
    expect(page).not.toContain('mqtt.subscription.note')
    expect(page).toContain('mqtt.receive.filter.all')
    expect(page).toContain('mqtt.receive.filter.in')
    expect(page).toContain('mqtt.receive.filter.out')
    expect(page).toContain('mqttMessageStats')
    expect(page).not.toContain('mqtt-stat-count')
    expect(page).toContain('mqtt-status-indicator')
    expect(page).toContain('mqtt-status-rect')
    expect(page).toContain('mqtt-connection-address-title')
    expect(page).toContain('<strong class="mqtt-connection-address-title" data-quick-jump-anchor')
    expect(page).toContain('mqtt-topic-filter-button')
    expect(page).toContain('mqtt-topic-filter-menu')
    expect(page).toContain('mqtt-topic-filter-search')
    expect(page).toContain('data-role="mqtt-topic-filter"')
    expect(page).toContain('mqtt.topicFilter.focus')
    expect(page).toContain('mqtt.topicFilter.search.set')
    expect(page).toContain('mqtt.topicFilter.select')
    expect(page).not.toContain('topic: {{ activeSubscriptionLabel }}')
    expect(page).not.toContain('mqtt-topic-filter-chip')
    expect(page).toContain('mqtt-command-bar')
    expect(page).not.toContain('mqtt-jump-strip')
    expect(page).not.toContain('mqtt-jump-chip')
    expect(page).toContain('mqtt-record-mode-buttons')
    expect(page).toContain('mqtt-record-mode-panel')
    expect(page).toContain('mqtt-record-toolbar-slot')
    expect(page).toContain('mqtt-record-toolbar-search')
    expect(page).toContain('mqtt-compact-filter-buttons')
    expect(page).toContain('mqtt.focus.templates')
    expect(page).toContain('activeMqttToolbarFilter')
    expect(page).toContain('mqtt-workspace-filter-mark')
    expect(page).toContain('activeMqttInfoIcon')
    expect(page).toContain(":class=\"[{ active: activeMqttToolbarFilter === item.id }, `mqtt-filter-button-${item.id}`]\"")
    expect(page).toContain(':aria-pressed="activeMqttToolbarFilter === item.id"')
    expect(page).toContain(":class=\"{ active: activeMqttToolbarFilter === 'favorites' }\"")
    expect(page).toContain(':aria-pressed="activeMqttToolbarFilter === \'favorites\'"')
    expect(page).not.toContain(':class="{ active: props.snapshot.mqttReceiveFilter === item.id }"')
    expect(page).not.toContain(":class=\"{ active: props.snapshot.activeMqttRecordList === 'templates' }\"")
    expect(page).toContain('mqtt.layout.toggle')
    const commandBarStart = page.indexOf('class="mqtt-workspace-toolbar mqtt-command-bar"')
    const commandBarEnd = page.indexOf('</header>', commandBarStart)
    const commandBar = page.slice(commandBarStart, commandBarEnd)
    expect(commandBar).not.toContain('mqtt.focus.messages')
    expect(commandBar).not.toContain('mqtt.focus.publish')
    expect(commandBar).toContain('mqtt.focus.templates')
    expect(commandBar).not.toContain('mqtt.publish.records.toggle')
    expect(commandBar).not.toContain('mqtt.log.drawer.open')
    expect(commandBar).toContain('mqtt.layout.toggle')
    expect(commandBar).toContain('mqtt-record-toolbar-search')
    const filterButtonsStart = commandBar.indexOf('<span class="mqtt-filter-buttons"')
    const filterButtonsEnd = commandBar.indexOf('</span>', filterButtonsStart)
    const filterButtons = commandBar.slice(filterButtonsStart, filterButtonsEnd)
    expect(filterButtons).not.toContain('mqtt-record-mode-buttons')
    expect(commandBar).toMatch(/<\/span>\s*<span class="mqtt-record-mode-buttons" aria-label="记录视图">/)
    expect(page).not.toContain('receiveFilterLabel')
    expect(page).toContain('接收')
    expect(page).toContain('发送')
    expect(page).not.toContain('mqtt.publish.records.toggle')
    expect(page).toContain('mqtt.publish.draft.toggle')
    expect(page).toContain('mqtt.publish.draft.saveDraft')
    expect(page).toContain("commandTitle('发送草稿', 'mqtt.publish.draft.toggle', 'c-h')")
    expect(page).toContain("commandTitle('保存当前草稿', 'mqtt.publish.draft.saveDraft', 'c-s-h')")
    expect(page).not.toContain("commandTitle('发送草稿', 'mqtt.publish.draft.toggle', 'c-l')")
    expect(page).not.toContain("commandTitle('保存当前草稿', 'mqtt.publish.draft.saveDraft', 'c-s-l')")
    expect(page).not.toContain('mqtt.publish.history')
    expect(page).toContain('MqttPublishRecordList')
    expect(page).toContain(':title="activeRecordListTitle"')
    expect(page).not.toContain(':search="activeRecordListSearch"')
    expect(page).not.toContain('@search="(query) => searchPublishRecords(activePublishRecordListId, query)"')
    expect(page).not.toContain('mqtt-publish-record-grid')
    expect(page).toContain('mqtt.publish.template.apply')
    expect(page).toContain('mqtt.publish.template.send')
    expect(page).toContain('mqtt.publish.draft.apply')
    expect(page).toContain('mqtt.publish.draft.send')
    expect(page).toContain('mqtt.publish.draft.toggleSelect')
    expect(page).toContain('mqtt.publish.draft.favorite')
    expect(page).toContain('mqtt.publish.draft.edit')
    expect(page).toContain('mqtt.publish.draft.rename')
    expect(page).toContain('mqtt.publish.draft.delete')
    expect(page).toContain('mqtt.publish.draft.clear')
    expect(page).toContain('mqtt.publish.draft.edit.save')
    expect(page).toContain('mqtt.publish.draft.edit.cancel')
    expect(page).toContain('mqttPublishDraftHistorySelectedIds')
    expect(page).toContain('mqtt-publish-draft-check')
    expect(page).toContain('publishDraftHistorySelected')
    expect(page).toContain("emit('dispatch', 'mqtt.detail.open', publishDraftHistoryRowArgs(row))")
    expect(page).toContain("emit('dispatch', 'mqtt.drawer.open', publishDraftHistoryRowArgs(row))")
    expect(page).toContain('mqtt-publish-draft-edit-modal')
    expect(page).toContain('data-role="mqtt-publish-draft-editor"')
    expect(page).toContain('data-mqtt-publish-draft-field="title"')
    expect(page).toContain('data-mqtt-publish-draft-field="note"')
    expect(page).toContain('data-mqtt-publish-draft-field="topic"')
    expect(page).toContain('data-mqtt-publish-draft-field="payload"')
    expect(page).not.toContain("window.prompt('草稿别名'")
    expect(page).not.toContain('@click="applyPublishDraftHistory(row)"')
    expect(page).toContain('mqtt.publish.options.open')
    expect(page).toContain('mqtt-publish-options-popover')
    expect(page).toContain('mqtt-publish-draft-popover')
    expect(page).toContain('data-role="mqtt-publish-draft"')
    expect(page).toContain('handlePublishDraftHistoryOutsidePointerdown')
    expect(page).toContain("document.addEventListener('pointerdown', handlePublishDraftHistoryOutsidePointerdown, true)")
    expect(page).toContain("document.removeEventListener('pointerdown', handlePublishDraftHistoryOutsidePointerdown, true)")
    expect(page).toContain("target.closest('.mqtt-publish-draft-anchor')")
    expect(page).toContain("emit('dispatch', 'mqtt.publish.draft.close')")
    expect(page).toContain('handlePublishOptionsOutsidePointerdown')
    expect(page).toContain("document.addEventListener('pointerdown', handlePublishOptionsOutsidePointerdown, true)")
    expect(page).toContain("document.removeEventListener('pointerdown', handlePublishOptionsOutsidePointerdown, true)")
    expect(page).toContain("target.closest('.mqtt-publish-options-anchor')")
    expect(page).toContain("emit('dispatch', 'mqtt.publish.options.close')")
    expect(page).toContain(":title=\"commandTitle('发送选项', 'mqtt.publish.options.open')\"")
    expect(page).not.toContain("commandTitle('发送选项', 'mqtt.publish.options.open', 'c-→')")
    expect(page).toContain('function isPlainEscape(event: KeyboardEvent, key: string)')
    for (const handlerName of [
      'handleSubscriptionEditorKeydown',
      'handleRecordEditorKeydown',
      'handlePublishDraftHistoryEditorKeydown',
      'handleConfigEditorKeydown'
    ]) {
      const source = functionSource(handlerName)
      expect(source).toContain('if (isPlainEscape(event, key))')
      expect(source).not.toMatch(/\n  event\.stopPropagation\(\)\n}/)
    }
    expect(page).toContain('mqtt-publish-draft-row')
    expect(page).toContain(':data-mqtt-preview-target="previewTargetValue(\'publish-draft-history\', row.id)"')
    expect(page).toContain(':data-quick-jump-label="publishDraftHistoryTitle(row)"')
    expect(page).toContain(':data-quick-jump-search="`${row.topic} ${payloadSnippet(row.payload)}`"')
    expect(page).toContain('<strong data-quick-jump-anchor>{{ publishDraftHistoryTitle(row) }}</strong>')
    expect(page).toContain('@mouseenter="enterPublishDraftHistoryPopover"')
    expect(page).toContain('@mousemove.passive="handlePublishDraftHistoryPointerMove"')
    expect(page).toContain('openShiftPreviewForTarget(activePublishDraftHistoryPreviewTarget())')
    expect(page).toContain("props.snapshot.mqttArchive.publishDraftHistory.find((item) => item.id === preview.targetId)")
    expect(page).toContain("emit('dispatch', 'mqtt.publish.draft.send', publishDraftHistoryRowArgs(row))")
    expect(page).not.toContain('mqtt-publish-history')
    expect(page).toContain('<MqttIcon name="draft" />')
    expect(page).not.toContain('<MqttIcon name="history" />')
    expect(page).toContain('formatPublishDraftHistoryTime')
    expect(page).toContain('data-role="mqtt-publish-options"')
    expect(page).toContain('data-mqtt-publish-field="topic"')
    expect(page).toContain('data-mqtt-publish-field="payload"')
    expect(page).toContain("let selector = props.snapshot.mqttPublishRecordsOpen ? '.mqtt-publish-record-list' : '.mqtt-message-list'")
    expect(page).toContain('mqtt.template.search.set')
    expect(page).toContain('mqtt.history.search.set')
    expect(page).toContain('mqtt.focus.messages')
    expect(page).toContain('mqtt.record.toggleSelect')
    expect(page).toContain('mqtt.record.repeatSend')
    expect(page).toContain('mqtt.focus.publish')
    expect(page).toContain('mqtt.record.favorite')
    expect(page).toContain('mqtt.record.copyTopic')
    expect(page).toContain('mqtt.record.copyPayload')
    expect(page).toContain('@contextmenu.prevent')
    expect(page).not.toContain('class="mqtt-send-actions"')
    expect(page).toContain('class="mqtt-publish-actions"')
    const publishActionsStart = page.indexOf('<span class="mqtt-publish-actions" aria-label="发送操作">')
    const publishActionsEnd = page.indexOf('</span>', publishActionsStart)
    const publishActions = page.slice(publishActionsStart, publishActionsEnd)
    expect(publishActions).toContain('mqtt.publish.draft.toggle')
    expect(publishActions).toContain('mqtt.publish.send')
    expect(publishActions).not.toContain('title="保存模板"')
    expect(publishActions).not.toContain('<MqttIcon name="star" />')
    expect(publishRecordList).toContain('class="mqtt-publish-record-list"')
    expect(publishRecordList).toContain('tabindex="-1"')
    expect(publishRecordList).toContain('role="option"')
    expect(publishRecordList).toContain(':data-quick-jump-label="rowRouteLabel(row)"')
    expect(publishRecordList).toContain(':data-quick-jump-search="`${rowTopic(row)} ${payloadSnippet(row.payload)}`"')
    expect(publishRecordList).not.toContain('mqtt-publish-record-list-header')
    expect(publishRecordList).not.toContain('mqtt-publish-record-list-search')
    expect(publishRecordList).not.toContain('搜索${title}')
    expect(publishRecordList).not.toContain('state.selectedIds.length')
    expect(publishRecordList).toContain('emit(\'toggleSelect\', row, $event.shiftKey)')
    expect(publishRecordList).not.toContain('mqtt.focus.templates')
    expect(publishRecordList).not.toContain('mqtt.record.repeatSend')
    expect(publishRecordList).not.toContain('mqtt.record.delete')
    expect(publishRecordList).not.toContain('class="mqtt-message-actions"')
    expect(publishRecordList).toContain('@dblclick="emit(\'toggleSelect\', row, $event.shiftKey)"')
    expect(publishRecordList).toContain('buildMqttInlinePayloadPreviewSegments')
    expect(publishRecordList).toContain('payloadSnippetSegments(row.payload)')
    expect(publishRecordList).toContain('rowRouteLabel')
    expect(publishRecordList).toContain('<strong data-quick-jump-anchor :title="rowTopic(row)">{{ rowRouteLabel(row) }}</strong>')
    expect(publishRecordList).not.toContain('mqtt-topic-alias-badge')
    expect(publishRecordList).not.toContain('rowAliasPreview')
    expect(publishRecordList).toContain('topicVisual')
    expect(publishRecordList).toContain('--mqtt-topic-color')
    expect(page).toContain('mqtt-message-stream')
    expect(page).toContain(':data-quick-jump-label="messageRouteLabel(message)"')
    expect(page).toContain(':data-quick-jump-search="`${message.topic} ${payloadSnippet(message.payload)}`"')
    expect(page).toContain('<strong data-quick-jump-anchor :title="messageHoverTitle(message)">{{ messageRouteLabel(message) }}</strong>')
    expect(page).toContain('mqtt-message-bubble')
    expect(page).toContain('mqtt-message-direction')
    expect(page).toContain("name: `MqttDirectionGlyph${variant[0].toUpperCase()}${variant.slice(1)}`")
    expect(page).toContain('all: MqttDirectionGlyphAll')
    expect(page).toContain('in: MqttDirectionGlyphIn')
    expect(page).toContain('out: MqttDirectionGlyphOut')
    expect(page).not.toContain('<b>{{ directionLabel(message) }}</b>')
    expect(page).not.toContain('<b>{{ directionLabel(previewRecord) }}</b>')
    expect(page).not.toContain('{{ formatTime(message.timestamp) }}')
    expect(page).toContain('mqtt-message-route')
    expect(page).toContain('mqtt-message-flags')
    expect(page).toContain('mqtt-message-actions')
    expect(page).toContain('mqtt-preview-layer')
    expect(page).toContain('previewPositionStyle')
    expect(page).toContain('const previewPayloadRef = ref<HTMLElement | null>(null)')
    expect(page).toContain('const hoverPreviewTarget = ref<MqttPreviewTarget | null>(null)')
    expect(page).toContain('const hoverPreviewSuspendedByKeyboard = ref(false)')
    expect(page).toContain('const lastPreviewPointerPosition = ref<{ x: number | null; y: number | null }>({ x: null, y: null })')
    expect(page).toContain('data-mqtt-preview-target')
    expect(page).toContain('@mousemove.passive="handlePreviewPointerMove"')
    expect(page).toContain('mqtt.preview.open')
    expect(page).toContain('mqtt.preview.scroll.set')
    expect(page).toContain('handlePreviewWheel')
    expect(page).toContain('@wheel.prevent.stop="handlePreviewWheel"')
    expect(page).toContain('Math.abs(event.deltaY) >= Math.abs(event.deltaX) ? event.deltaY : event.deltaX')
    expect(page).toContain('clearPreviewCloseTimer()')
    expect(page).toContain('toolPreviewPrefs')
    expect(page).toContain('hoverPreviewEnabled')
    expect(page).toContain('hoverPreviewDelayMs')
    expect(page).not.toContain('mqtt.preview.hover.update')
    expect(page).not.toContain('悬浮预览')
    expect(page).not.toContain('预览延迟')
    expect(page).toContain("props.snapshot.toolPreviewPrefs.hoverPreviewEnabled")
    expect(page).toContain("props.snapshot.toolPreviewPrefs.hoverPreviewDelayMs")
    expect(page).toContain("if (source === 'shift')")
    expect(page).toContain('openShiftPreviewForTarget')
    expect(page).toContain('hoverPreviewSuspendedByKeyboard.value = false')
    expect(page).toContain('hoverPreviewSuspendedByKeyboard.value = true')
    expect(page).toContain('buildMqttPayloadPreviewSegments')
    expect(page).toContain('buildMqttInlinePayloadPreviewSegments')
    expect(page).toContain('ref="previewPayloadRef"')
    expect(page).toContain('@scroll.passive="syncPreviewScroll"')
    expect(page).toContain('mqtt-preview-payload')
    expect(page).toContain('mqtt-preview-payload-content')
    expect(page).not.toContain('transform: `translateY(-${props.snapshot.mqttPreview.scrollTop}px)`')
    expect(page).toContain('mqtt-preview-token')
    expect(page).toContain('mqtt-preview-direction')
    expect(page).toContain('mqtt-preview-topic')
    expect(page).toContain('mqtt-preview-time')
    expect(page).toContain("source: 'shift'")
    expect(page).toContain('props.shiftPreview')
    expect(page).toContain("props.snapshot.mqttPreview.source !== 'shift'")
    expect(page).toContain('mqtt-workspace-resizer')
    expect(page).toContain('resizeMqttLayout')
    expect(page).toContain('mqtt-item-payload-snippet')
    expect(page).toContain('payloadSnippetSegments(message.payload)')
    expect(page).toContain('messageRouteLabel')
    expect(page).toContain('<strong data-quick-jump-anchor :title="messageHoverTitle(message)">{{ messageRouteLabel(message) }}</strong>')
    expect(page).toContain('class="mqtt-message-time-badge"')
    expect(page).toContain(":class=\"{ 'is-today': timeParts.isToday, 'has-date': timeParts.date }\"")
    expect(page).toContain(':datetime="timeParts.iso"')
    expect(page).toContain(':aria-label="timeParts.full"')
    expect(page).toContain('v-if="timeParts.date"')
    expect(page).toContain('{{ timeParts.date }}')
    expect(page).toContain('{{ timeParts.time }}')
    expect(page).toContain('isSameCalendarDate')
    expect(page).toContain('formatFullDateTime')
    expect(page).toContain('date.getFullYear() === now.getFullYear()')
    expect(page).toContain('date.getSeconds()')
    expect(page).not.toContain('date.getMilliseconds()')
    expect(page).not.toContain('{{ timeParts.millis }}')
    expect(page).toContain("flags.join(' · ')")
    expect(page).not.toContain('topicAliasPreview')
    expect(page).not.toContain('mqtt-topic-alias-badge')
    expect(page).toContain('mqtt-message-bubble-in')
    expect(page).toContain('mqtt-message-bubble-out')
    expect(page).toContain('aria-label="新增订阅"')
    expect(page).toContain('aria-label="清空全部订阅"')
    expect(page).toContain('aria-label="发送 MQTT 消息"')
    expect(page).toContain('data-role="mqtt-publish-editor"')
    expect(page).toContain('mqttTopicVisual')
    expect(page).toContain('subscriptionColorPalette')
    expect(page).toContain('data-mqtt-config-subscription-field="color"')
    expect(page).not.toContain('data-role="mqtt-favorite-editor"')
    expect(page).toContain('data-role="mqtt-editor"')
    expect(page).toContain('ref="workbenchRef"')
    expect(page).toContain('data-mqtt-shortcut-hint')
    expect(page).toContain('shortcutHintEntries')
    expect(page).toContain('updateShortcutHintPositions')
    expect(page).toContain('layoutShortcutHints')
    expect(page).toContain('isVisibleShortcutHintAnchor')
    expect(page).toContain('<Teleport to="body">')
    expect(page).toContain('mqtt-shortcut-top-layer')
    expect(page).not.toContain('<kbd v-if="visibleCommandHint')
    const messageActionStart = page.indexOf('<span class="mqtt-message-actions" aria-label="消息操作">')
    const messageActionEnd = page.indexOf('</span>', messageActionStart)
    const messageActions = page.slice(messageActionStart, messageActionEnd)
    expect(messageActions).toContain('aria-label="预览消息"')
    expect(messageActions).toContain('mqtt.preview.open')
    expect(messageActions).toContain('aria-label="详情消息"')
    expect(messageActions).toContain('mqtt.detail.open')
    expect(messageActions).toContain('aria-label="快捷操作"')
    expect(messageActions).toContain('mqtt.drawer.open')
    expect(messageActions.match(/<button/g)).toHaveLength(3)
    expect(messageActions).not.toContain('复制主题')
    expect(messageActions).not.toContain('复制内容')
    expect(messageActions).not.toContain('再次发送')
    expect(messageActions).not.toContain('填入发布')
    expect(css).not.toMatch(/\.mqtt-message-actions \{[^}]*opacity:\s*0;/s)
    expect(css).not.toContain('.mqtt-message-row.focused .mqtt-message-actions')
    const subscriptionActionStart = page.indexOf('<span class="mqtt-subscription-row-actions" aria-label="订阅操作">')
    const subscriptionActionEnd = page.indexOf('</span>', subscriptionActionStart)
    const subscriptionActions = page.slice(subscriptionActionStart, subscriptionActionEnd)
    expect(subscriptionActions.match(/<button/g)).toHaveLength(3)
    expect(subscriptionActions).toContain('mqtt-subscription-copy')
    expect(subscriptionActions).toContain('mqtt-subscription-apply')
    expect(subscriptionActions).toContain('mqtt-subscription-more')
    expect(subscriptionActions).not.toContain('mqtt-subscription-detail')
    expect(subscriptionActions).not.toContain('mqtt-subscription-edit')
    expect(subscriptionActions).not.toContain('mqtt-subscription-delete')
    expect(css).not.toMatch(/\.mqtt-subscription-row-actions \{[^}]*opacity:\s*0;/s)
    expect(css).not.toContain('.mqtt-subscription-row:hover .mqtt-subscription-row-actions')
    expect(css).toMatch(/\.mqtt-subscription-row \{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+repeat\(3,\s*22px\);[^}]*min-height:\s*36px;/s)
    expect(css).not.toContain('grid-template-rows: 20px 22px')
    expect(css).not.toContain('min-height: 70px')
    expect(css).not.toMatch(/\.mqtt-subscription-row:hover\s+\.mqtt-subscription-route/)
    expect(css).toMatch(/\.mqtt-subscription-row\.focused \.mqtt-subscription-route,[^{]+\.mqtt-subscription-row\.active \.mqtt-subscription-route \{[^}]*opacity:\s*1;/s)
    expect(css).toMatch(/\.mqtt-subscription-row\.focused:not\(\.active\) \{[^}]*border-color:\s*#2f80ed;[^}]*background:\s*#eef6ff;/s)
    expect(css).toMatch(/\.mqtt-subscription-row-actions \{[^}]*grid-column:\s*2 \/ -1;[^}]*grid-template-columns:\s*repeat\(3,\s*22px\);/s)
    expect(css).toMatch(/\.mqtt-subscription-copy,[^{]+\.mqtt-subscription-more \{[^}]*width:\s*22px;[^}]*height:\s*22px;/s)
    expect(css).toContain('.mqtt-workbench-grid')
    expect(css).toContain('.mqtt-connection-rail')
    expect(css).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(css).toContain('.mqtt-subscription-rail')
    expect(css).toContain('.mqtt-message-workspace')
    expect(css).toContain('.mqtt-workspace-split')
    expect(css).toContain('.mqtt-panel-toggle')
    expect(css).toContain('.mqtt-message-row')
    expect(css).toContain('.mqtt-log-drawer')
    expect(css).toContain('.mqtt-log-detail')
    expect(css).toContain('.mqtt-subscription-row')
    expect(css).toContain('.mqtt-subscription-row.selected')
    expect(css).toContain('.mqtt-config-card.selected')
    expect(css).toContain('.mqtt-config-card:hover')
    expect(css).toContain('.mqtt-config-card:focus-visible')
    expect(css).toContain('.mqtt-subscription-unread')
    expect(css).toContain('.mqtt-subscription-route')
    expect(css).toContain('grid-template-columns: minmax(0, 1fr)')
    expect(css).toContain('.mqtt-subscription-shortcut-popover')
    expect(css).not.toContain('.mqtt-subscription-delete')
    expect(css).toContain('.mqtt-subscription-row-actions')
    expect(css).toContain('.mqtt-subscription-title-line')
    expect(css).toContain('.mqtt-subscription-rail .mqtt-rail-title > .mqtt-rail-actions')
    expect(css).toContain('flex-wrap: nowrap')
    expect(css).toContain('.mqtt-subscription-list')
    expect(css).toContain('.mqtt-subscription-editor')
    expect(css).toContain('.mqtt-subscription-modal')
    expect(css).not.toContain('.mqtt-publish-record-grid')
    expect(css).toContain('.mqtt-panel-title-actions')
    expect(css).toContain('.mqtt-publish-record-list')
    expect(css).toMatch(/\.mqtt-receive-panel \{[^}]*grid-template-rows:\s*minmax\(0,\s*1fr\);/s)
    expect(css).toMatch(/\.mqtt-filter-buttons button\.active \{[^}]*background:\s*#edf8f7;/s)
    expect(css).toContain('.mqtt-compact-filter-buttons')
    expect(css).toContain('box-shadow: inset 0 0 0 1px rgba(56, 106, 114, 0.18), 0 0 0 2px rgba(56, 106, 114, 0.08)')
    expect(css).toContain('.mqtt-record-checkbox')
    expect(css).not.toContain('.mqtt-send-actions')
    expect(css).toContain('.mqtt-config-drawer')
    expect(css).toContain('.mqtt-config-drawer-overlay')
    expect(css).toMatch(/\.mqtt-drawer-action \{[^}]*grid-template-columns:\s*28px\s+minmax\(0,\s*1fr\)\s+minmax\(0,\s*136px\);/s)
    expect(css).toMatch(/\.mqtt-drawer-action kbd \{[^}]*max-width:\s*136px;[^}]*white-space:\s*normal;[^}]*overflow-wrap:\s*anywhere;/s)
    expect(css).toContain('.mqtt-client-id-row')
    expect(css).toContain('.mqtt-endpoint-compact-row')
    expect(css).toContain('.mqtt-config-publish-row')
    expect(css).toContain('.mqtt-config-subscription-row.focused')
    expect(css).toContain('.mqtt-config-publish-row.focused')
    expect(css).toContain('.mqtt-config-options-panel')
    expect(css).toMatch(/\.mqtt-config-checkbox-grid \{[^}]*grid-column:\s*1\s*\/\s*-1;[^}]*display:\s*flex;[^}]*flex-wrap:\s*wrap;[^}]*justify-content:\s*flex-start;/s)
    expect(css).not.toMatch(/\.mqtt-config-checkbox-grid \{[^}]*justify-content:\s*space-between;/s)
    expect(css).toMatch(/\.mqtt-config-checkbox-grid \.checkbox-line \{[^}]*display:\s*inline-flex\s*!important;[^}]*white-space:\s*nowrap;/s)
    expect(css).toMatch(/\.mqtt-config-checkbox-grid input\[type='checkbox'\] \{[^}]*width:\s*16px;[^}]*flex:\s*0\s+0\s+16px;/s)
    expect(css).toContain('.mqtt-icon-button')
    expect(css).toContain('.mqtt-collapsed-logo')
    expect(css).toContain('.mqtt-record-toolbar-search')
    expect(css).toContain('.mqtt-command-bar')
    expect(css).toContain('.mqtt-status-indicator')
    expect(css).toContain('.mqtt-status-rect')
    expect(css).toContain('.mqtt-status-connected')
    expect(css).toContain('.mqtt-status-error')
    expect(css).toContain('.mqtt-topic-filter-button')
    expect(css).toContain('.mqtt-topic-filter-menu')
    expect(css).toContain('.mqtt-topic-filter-option')
    expect(css).toContain('.mqtt-publish-options-popover')
    expect(css).toContain('--z-workbench-popover')
    expect(css).toContain('--z-workbench-popover-active')
    expect(css).toContain('--z-drawer-overlay')
    expect(css).toContain('--z-floating-preview')
    expect(css).toMatch(/\.drawer-overlay \{[^}]*z-index:\s*var\(--z-drawer-overlay\);/s)
    expect(css).toMatch(/\.mqtt-message-workspace \{[^}]*overflow:\s*visible;/s)
    expect(css).toMatch(/\.mqtt-workspace-body \{[^}]*overflow:\s*visible;/s)
    expect(css).toMatch(/\.mqtt-workspace-resizer \{[^}]*z-index:\s*var\(--z-workbench-control\);/s)
    expect(css).toMatch(/\.mqtt-topic-filter-menu \{[^}]*z-index:\s*var\(--z-workbench-popover-active\);/s)
    expect(css).toMatch(/\.mqtt-publish-options-popover \{[^}]*z-index:\s*var\(--z-workbench-popover-active\);/s)
    expect(css).toMatch(/\.mqtt-publish-draft-popover \{[^}]*z-index:\s*var\(--z-workbench-popover-active\);/s)
    expect(css).toMatch(/\.mqtt-send-panel \{[^}]*position:\s*relative;[^}]*z-index:\s*var\(--z-workbench-panel-active\);[^}]*overflow:\s*visible;/s)
    expect(css).toContain('.mqtt-publish-option-row')
    expect(css).toContain('.mqtt-message-row.selected::before')
    expect(css).toContain('grid-template-columns: minmax(132px, 0.82fr) minmax(96px, 0.58fr) max-content')
    expect(css).not.toContain('.mqtt-jump-strip')
    expect(css).not.toContain('.mqtt-jump-chip')
    expect(css).toContain('.mqtt-record-mode-buttons')
    expect(css).toContain('grid-template-columns: repeat(2, 26px)')
    expect(css).toMatch(/\.mqtt-record-mode-buttons \.mqtt-filter-button \{[^}]*width:\s*26px;[^}]*min-width:\s*26px;[^}]*height:\s*26px;[^}]*padding:\s*0;/s)
    expect(css).toContain('.mqtt-record-mode-panel')
    expect(css).toContain('.mqtt-message-stream')
    expect(css).not.toContain('.mqtt-message-timeline::before')
    expect(css).toContain('.mqtt-message-bubble')
    expect(css).toContain('--mqtt-row-height: 31px')
    expect(css).toMatch(/\.mqtt-message-bubble,\s*\.mqtt-publish-record-row \{[^}]*height:\s*var\(--mqtt-row-height\);[^}]*max-height:\s*var\(--mqtt-row-height\);[^}]*overflow:\s*hidden;/s)
    expect(css).toContain('.mqtt-direction-glyph')
    expect(css).toContain('.mqtt-workspace-filter-mark')
    expect(css).toContain('.mqtt-message-direction .mqtt-direction-glyph')
    expect(css).toContain('.mqtt-preview-direction .mqtt-direction-glyph')
    expect(css).toContain('.mqtt-filter-button-incoming:not(.active)')
    expect(css).toContain('.mqtt-filter-button-outgoing:not(.active)')
    expect(css).toContain('.mqtt-message-row.focused.selected .mqtt-message-bubble')
    expect(css).toContain('.mqtt-message-route strong')
    expect(css).toContain('.mqtt-message-time-date')
    expect(css).toContain('.mqtt-message-time-clock')
    expect(css).toContain('.mqtt-message-time-badge.is-today')
    expect(css).toContain('.mqtt-message-time-badge.has-date')
    expect(css).toContain('.mqtt-message-row.incoming .mqtt-message-time-date')
    expect(css).toContain('.mqtt-message-row.incoming .mqtt-message-time-clock')
    expect(css).toContain('.mqtt-message-row.outgoing .mqtt-message-time-date')
    expect(css).toContain('.mqtt-message-row.outgoing .mqtt-message-time-clock')
    expect(css).not.toContain('.mqtt-topic-alias-badge')
    expect(css).toContain('.mqtt-topic-color-swatch')
    expect(css).toContain('.mqtt-topic-color-input')
    expect(css).toContain('--mqtt-topic-color')
    expect(css).toContain('.mqtt-preview-layer')
    expect(css).toContain('.mqtt-preview-payload')
    expect(css).toContain('.mqtt-preview-payload-content')
    expect(css).toContain('.mqtt-preview-token-key')
    expect(css).toContain('.drawer-overlay-left')
    expect(css).toContain('.mqtt-detail-drawer')
    expect(css).toContain('.mqtt-item-payload-snippet')
    expect(css).toContain('.mqtt-message-bubble-in')
    expect(css).toContain('.mqtt-message-bubble-out')
    expect(css).toContain('width: 100%')
    expect(css).not.toContain('width: min(66.666%, 980px)')
    expect(css).toContain('.mqtt-publish-command-bar')
    expect(css).toContain('.mqtt-publish-actions')
    expect(css).toMatch(/\.mqtt-publish-actions \{[^}]*grid-template-columns:\s*repeat\(2,\s*24px\);/s)
    expect(css).not.toMatch(/\.mqtt-publish-record-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
    expect(css).not.toContain('grid-template-areas:')
    expect(css).not.toContain('"summary records"')
    expect(css).not.toContain('"filters filters"')
    expect(css).toMatch(/@media \(max-width: 1100px\) \{[\s\S]*\.mqtt-command-bar \{[\s\S]*grid-template-columns:\s*minmax\(118px,\s*0\.78fr\)\s*minmax\(92px,\s*0\.58fr\)\s*max-content;/s)
    expect(css).toMatch(/@media \(max-width: 1100px\) \{[\s\S]*\.mqtt-publish-command-bar \{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*24px\s*max-content;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*body \{[\s\S]*min-width:\s*0;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*\.mqtt-command-bar \{[\s\S]*grid-template-columns:\s*118px\s*minmax\(92px,\s*1fr\)\s*82px;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*\.mqtt-command-bar \{[\s\S]*overflow-x:\s*auto;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*\.mqtt-publish-command-bar \{[\s\S]*grid-template-columns:\s*minmax\(150px,\s*1fr\)\s*24px\s*max-content;/s)
    expect(css).toContain('.mqtt-workspace-resizer')
    expect(css).toContain('--mqtt-stack-receive-ratio')
    expect(css).toContain('--mqtt-split-receive-ratio')
    expect(css).toContain('--z-shortcut-top-layer')
    expect(css).toContain('.mqtt-shortcut-top-layer')
    expect(css).toMatch(/\.mqtt-shortcut-badge \{[^}]*position:\s*fixed;/s)
    expect(css).toMatch(/\.mqtt-shortcut-badge \{[^}]*z-index:\s*var\(--z-shortcut-top-layer\);/s)
    expect(css).toContain('position: fixed')
    expect(css).toContain('--mqtt-preview-left')
    expect(css).toContain('--mqtt-preview-top')
    expect(css).toContain('--mqtt-preview-max-height')
    expect(css).toContain('height: 100dvh')
    expect(css).toContain('.app-shell')
    expect(css).toContain('.tab-content')
    const media900Index = css.indexOf('@media (max-width: 900px)')
    const media700Index = css.indexOf('@media (max-width: 700px)')
    expect(media700Index).toBeGreaterThan(media900Index)
    expect(css.slice(media900Index, media700Index)).not.toContain('.mqtt-workbench-grid')
    const previewCss = css.slice(css.indexOf('.mqtt-preview-layer'), css.indexOf('.mqtt-preview-layer header'))
    expect(previewCss).not.toContain('right: 18px')
    expect(previewCss).not.toContain('top: 72px')
    expect(previewCss).toContain('width: var(--mqtt-preview-width, min(420px, calc(100vw - 16px)))')
    expect(previewCss).toContain('min-height: 160px')
    const previewPayloadStart = css.indexOf('.mqtt-preview-payload')
    const previewPayloadCss = css.slice(previewPayloadStart, css.indexOf('.mqtt-preview-token', previewPayloadStart))
    expect(previewPayloadCss).toContain('overflow: auto')
    expect(previewPayloadCss).toContain('font-size: 12px')
    expect(previewPayloadCss).not.toContain('transition: transform')
  })
})
