import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('mqtt page layout', () => {
  it('is lazy-loaded and exposes compact MQTT workbench surfaces', () => {
    const app = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')
    const page = readFileSync(resolve(process.cwd(), 'src/pages/MqttPage.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')

    expect(app).toContain("defineAsyncComponent(() => import('./pages/MqttPage.vue'))")
    expect(app).toContain('<template #mqtt>')
    expect(page).toContain('class="mqtt-workbench-grid"')
    expect(page).toContain('mqtt-connection-rail')
    expect(page).toContain('mqtt-subscription-rail')
    expect(page).toContain('mqtt-message-workspace')
    expect(page).toContain('mqtt-workspace-split')
    expect(page).toContain('mqtt-panel-toggle')
    expect(page).toContain('mqtt.subscription.panel.toggle')
    expect(page).toContain('mqtt.layout.toggle')
    expect(page).toContain('mqtt.connection.connect')
    expect(page).toContain('mqtt.publish.send')
    expect(page).toContain('mqtt.record.resendDraft')
    expect(page).toContain('autoReconnect')
    expect(page).toContain('reconnectPeriodMs')
    expect(page).toContain('connectTimeoutMs')
    expect(page).toContain('keepaliveSec')
    expect(page).toContain('syncRecords')
    expect(page).toContain('服务器地址')
    expect(page).toContain('data-mqtt-field="host"')
    expect(page).toContain('data-mqtt-field="port"')
    expect(page).toContain('data-mqtt-field="path"')
    expect(page).toContain('SSL/TLS')
    expect(page).toContain('当前连接地址')
    expect(page).toContain('mqtt-endpoint-preview')
    expect(page).toContain('mqtt-log-drawer')
    expect(page).toContain('focusLog')
    expect(page).toContain('mqtt.log.drawer.open')
    expect(page).toContain('mqtt.log.clearAll')
    expect(page).toContain('mqtt.log.clearCurrentConfig')
    expect(page).toContain('mqtt.log.delete')
    expect(page).toContain('日志详情')
    expect(page).toContain('清空本连接')
    expect(page).toContain('清空全部')
    expect(page).toContain('错误日志')
    expect(page).toContain('订阅')
    expect(page).toContain('添加订阅')
    expect(page).toContain('mqtt-subscription-list')
    expect(page).toContain('mqtt-subscription-delete')
    expect(page).toContain('mqtt.subscription.toggleSelect')
    expect(page).toContain('mqtt.subscription.applyFilter')
    expect(page).toContain('mqtt.subscription.deleteSelected')
    expect(page).toContain('mqtt.subscription.clearAll')
    expect(page).toContain('mqttSubscriptionDraft')
    expect(page).toContain('mqtt-subscription-modal')
    expect(page).toContain('mqtt-subscription-editor-row')
    expect(page).toContain('mqtt.subscription.editor.open')
    expect(page).toContain('mqtt.subscription.editor.save')
    expect(page).toContain('mqtt.subscription.editor.cancel')
    expect(page).toContain('data-role="mqtt-subscription-editor"')
    expect(page).toContain(':key="item.id"')
    expect(page).not.toContain(':key="`${index}:${item.topic}`"')
    expect(page).toContain('订阅管理')
    expect(page).toContain('订阅别名')
    expect(page).toContain('管理订阅')
    expect(page).toContain('未读')
    expect(page).toContain('mqtt.subscription.select')
    expect(page).not.toContain('mqtt.subscription.note')
    expect(page).toContain('mqtt.receive.filter.all')
    expect(page).toContain('mqtt.receive.filter.in')
    expect(page).toContain('mqtt.receive.filter.out')
    expect(page).toContain('接收')
    expect(page).toContain('发送')
    expect(page).toContain('发送记录')
    expect(page).toContain('mqtt.publish.records.toggle')
    expect(page).toContain('mqtt.publish.template.save')
    expect(page).toContain('mqtt.publish.template.apply')
    expect(page).toContain('mqtt.publish.template.send')
    expect(page).toContain('data-role="mqtt-search"')
    expect(page).toContain('data-role="mqtt-editor"')
    expect(css).toContain('.mqtt-workbench-grid')
    expect(css).toContain('.mqtt-connection-rail')
    expect(css).toContain('.mqtt-subscription-rail')
    expect(css).toContain('.mqtt-message-workspace')
    expect(css).toContain('.mqtt-workspace-split')
    expect(css).toContain('.mqtt-panel-toggle')
    expect(css).toContain('.mqtt-message-row')
    expect(css).toContain('.mqtt-log-drawer')
    expect(css).toContain('.mqtt-log-detail')
    expect(css).toContain('.mqtt-subscription-row')
    expect(css).toContain('.mqtt-subscription-row.selected')
    expect(css).toContain('.mqtt-subscription-delete')
    expect(css).toContain('.mqtt-subscription-list')
    expect(css).toContain('.mqtt-subscription-editor')
    expect(css).toContain('.mqtt-subscription-modal')
    expect(css).toContain('.mqtt-publish-records')
    expect(css).toContain('.mqtt-endpoint-preview')
    const media900Index = css.indexOf('@media (max-width: 900px)')
    const media700Index = css.indexOf('@media (max-width: 700px)')
    expect(media700Index).toBeGreaterThan(media900Index)
    expect(css.slice(media900Index, media700Index)).not.toContain('.mqtt-workbench-grid')
  })
})
