import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('mqtt page layout', () => {
  it('is lazy-loaded and exposes compact MQTT workbench surfaces', () => {
    const app = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')
    const page = readFileSync(resolve(process.cwd(), 'src/pages/MqttPage.vue'), 'utf8')
    const publishRecordList = readFileSync(resolve(process.cwd(), 'src/components/MqttPublishRecordList.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')

    expect(app).toContain("defineAsyncComponent(() => import('./pages/MqttPage.vue'))")
    expect(app).toContain('<template #mqtt>')
    expect(page).toContain('class="mqtt-workbench-grid"')
    expect(page).toContain('mqtt-connection-rail')
    expect(page).toContain('mqtt-subscription-rail')
    expect(page).toContain('mqtt-message-workspace')
    expect(page).toContain('mqtt-workspace-split')
    expect(page).toContain('mqtt-panel-toggle')
    expect(page).toContain('mqtt.subscription.panel.toggle')
    expect(page).toContain('mqtt.layout.toggle')
    expect(page).toContain('mqtt.connection.connect')
    expect(page).toContain('mqtt.publish.send')
    expect(page).toContain('mqtt.record.resendDraft')
    expect(page).toContain('autoReconnect')
    expect(page).toContain('reconnectPeriodMs')
    expect(page).toContain('connectTimeoutMs')
    expect(page).toContain('keepaliveSec')
    expect(page).toContain('syncRecords')
    expect(page).toContain('服务器地址')
    expect(page).toContain('data-mqtt-field="host"')
    expect(page).toContain('data-mqtt-field="port"')
    expect(page).toContain('data-mqtt-field="path"')
    expect(page).toContain('mqtt-config-drawer')
    expect(page).toContain('mqtt-config-drawer-overlay')
    expect(page).toContain('addConfigSubscriptionItem')
    expect(page).toContain('updateConfigSubscriptionItem')
    expect(page).toContain('removeConfigSubscriptionItem')
    expect(page).toContain('data-mqtt-field="subscriptions"')
    expect(page).toContain('placeholder="订阅别名"')
    expect(page).toContain('placeholder="plc/+/status"')
    expect(page).toContain('role="dialog"')
    expect(page).toContain('aria-modal="true"')
    expect(page).not.toContain('<section v-if="props.snapshot.mqttConfigDraft" class="mqtt-config-editor"')
    expect(page).not.toContain('<section v-else class="mqtt-workspace-body">')
    expect(page).toContain('SSL/TLS')
    expect(page).toContain('当前连接地址')
    expect(page).toContain('mqtt-endpoint-preview')
    expect(page).toContain('mqtt-log-drawer')
    expect(page).toContain('focusLog')
    expect(page).toContain('mqtt.log.drawer.open')
    expect(page).toContain('mqtt.log.clearAll')
    expect(page).toContain('mqtt.log.clearCurrentConfig')
    expect(page).toContain('mqtt.log.delete')
    expect(page).toContain('日志详情')
    expect(page).toContain('清空本连接')
    expect(page).toContain('清空全部')
    expect(page).toContain('错误日志')
    expect(page).toContain('订阅')
    expect(page).toContain('添加订阅')
    expect(page).toContain('mqtt-subscription-list')
    expect(page).toContain('mqtt-subscription-delete')
    expect(page).toContain('mqtt.subscription.toggleSelect')
    expect(page).toContain('mqtt.subscription.applyFilter')
    expect(page).toContain('mqtt.subscription.deleteSelected')
    expect(page).toContain('mqtt.subscription.clearAll')
    expect(page).toContain('mqttSubscriptionDraft')
    expect(page).toContain('mqttFavoriteDraft')
    expect(page).toContain('mqtt-subscription-modal')
    expect(page).toContain('mqtt-subscription-editor-row')
    expect(page).toContain('mqtt.subscription.editor.open')
    expect(page).not.toContain(':disabled="!activeConfig" title="管理订阅"')
    expect(page).toContain('mqtt.subscription.editor.save')
    expect(page).toContain('mqtt.subscription.editor.cancel')
    expect(page).toContain('data-role="mqtt-subscription-editor"')
    expect(page).toContain('data-mqtt-subscription-item-id')
    expect(page).toContain('activeItemId')
    expect(page).not.toContain('document.querySelector<HTMLInputElement>(`[data-mqtt-subscription-field="${field}"]`)')
    expect(page).not.toContain('watch(() => [props.snapshot.mqttSubscriptionDraft?.activeItemId, props.snapshot.mqttSubscriptionDraft?.activeField] as const')
    expect(page).toContain('const alreadyFocused = document.activeElement === input')
    expect(page).toContain('if (!alreadyFocused) input?.setSelectionRange(input.value.length, input.value.length)')
    expect(page).not.toContain("topic: '#'")
    expect(page).toContain(':key="item.id"')
    expect(page).not.toContain(':key="`${index}:${item.topic}`"')
    expect(page).toContain('订阅管理')
    expect(page).toContain('订阅别名')
    expect(page).toContain('mqtt-config-subscription-list')
    expect(page).toContain('mqtt-config-subscription-row')
    expect(page).toContain('data-mqtt-config-subscription-index')
    expect(page).toContain('data-mqtt-config-subscription-field="topic"')
    expect(page).toContain('暂无订阅 topic，可在这里添加')
    expect(page).not.toContain('title="管理订阅"')
    expect(page).toContain('mqtt-subscription-unread')
    expect(page).toContain('mqtt.subscription.select')
    expect(page).not.toContain('mqtt.subscription.note')
    expect(page).toContain('mqtt.receive.filter.all')
    expect(page).toContain('mqtt.receive.filter.in')
    expect(page).toContain('mqtt.receive.filter.out')
    expect(page).toContain('mqttMessageStats')
    expect(page).toContain('mqtt-stat-count')
    expect(page).toContain('mqtt-topic-filter-chip')
    expect(page).toContain('mqtt-command-bar')
    expect(page).not.toContain('mqtt-jump-strip')
    expect(page).not.toContain('mqtt-jump-chip')
    expect(page).toContain('mqtt-record-mode-buttons')
    expect(page).toContain('mqtt-record-mode-panel')
    expect(page).toContain('mqtt.focus.templates')
    expect(page).toContain('mqtt.layout.toggle')
    const commandBarStart = page.indexOf('class="mqtt-workspace-toolbar mqtt-command-bar"')
    const commandBarEnd = page.indexOf('</header>', commandBarStart)
    const commandBar = page.slice(commandBarStart, commandBarEnd)
    expect(commandBar).not.toContain('mqtt.focus.messages')
    expect(commandBar).not.toContain('mqtt.focus.publish')
    expect(commandBar).toContain('mqtt.focus.templates')
    expect(commandBar).toContain('mqtt.publish.records.toggle')
    expect(commandBar).not.toContain('mqtt.log.drawer.open')
    expect(commandBar).toContain('mqtt.layout.toggle')
    const filterButtonsStart = commandBar.indexOf('<span class="mqtt-filter-buttons"')
    const filterButtonsEnd = commandBar.indexOf('</span>', filterButtonsStart)
    const filterButtons = commandBar.slice(filterButtonsStart, filterButtonsEnd)
    expect(filterButtons).not.toContain('mqtt-record-mode-buttons')
    expect(commandBar).toMatch(/<\/span>\s*<span class="mqtt-record-mode-buttons" aria-label="记录视图">/)
    expect(page).not.toContain('receiveFilterLabel')
    expect(page).toContain('接收')
    expect(page).toContain('发送')
    expect(page).toContain('mqtt.publish.records.toggle')
    expect(page).toContain('MqttPublishRecordList')
    expect(page).toContain(':title="activeRecordListTitle"')
    expect(page).not.toContain('mqtt-publish-record-grid')
    expect(page).toContain('mqtt.publish.template.save')
    expect(page).toContain('mqtt.publish.template.apply')
    expect(page).toContain('mqtt.publish.template.send')
    expect(page).toContain('mqtt.template.search.set')
    expect(page).toContain('mqtt.history.search.set')
    expect(page).toContain('mqtt.focus.messages')
    expect(page).toContain('mqtt.record.toggleSelect')
    expect(page).toContain('mqtt.record.repeatSend')
    expect(page).toContain('mqtt.focus.publish')
    expect(page).toContain('mqtt.record.favorite')
    expect(page).toContain('mqtt.record.copyTopic')
    expect(page).toContain('mqtt.record.copyPayload')
    expect(page).toContain('@contextmenu.prevent')
    expect(page).not.toContain('class="mqtt-send-actions"')
    expect(page).toContain('class="mqtt-publish-actions"')
    expect(publishRecordList).toContain('class="mqtt-publish-record-list"')
    expect(publishRecordList).toContain('搜索${title}')
    expect(publishRecordList).toContain('state.selectedIds.length')
    expect(publishRecordList).toContain('emit(\'toggleSelect\', row, $event.shiftKey)')
    expect(publishRecordList).toContain('mqtt.focus.templates')
    expect(publishRecordList).toContain('mqtt.record.repeatSend')
    expect(publishRecordList).toContain('mqtt.record.delete')
    expect(publishRecordList).toContain('buildMqttInlinePayloadPreviewSegments')
    expect(publishRecordList).toContain('payloadSnippetSegments(row.payload)')
    expect(publishRecordList).toContain('mqtt-topic-alias-badge')
    expect(page).toContain('mqtt-message-stream')
    expect(page).toContain('mqtt-message-bubble')
    expect(page).toContain('mqtt-message-direction')
    expect(page).toContain('mqtt-message-route')
    expect(page).toContain('mqtt-message-flags')
    expect(page).toContain('mqtt-message-actions')
    expect(page).toContain('mqtt-preview-layer')
    expect(page).toContain('previewPositionStyle')
    expect(page).toContain('const previewPayloadRef = ref<HTMLElement | null>(null)')
    expect(page).toContain('data-mqtt-preview-target')
    expect(page).toContain('mqtt.preview.open')
    expect(page).toContain('mqtt.preview.scroll.set')
    expect(page).toContain('toolPreviewPrefs')
    expect(page).toContain('hoverPreviewEnabled')
    expect(page).toContain('hoverPreviewDelayMs')
    expect(page).not.toContain('mqtt.preview.hover.update')
    expect(page).not.toContain('悬浮预览')
    expect(page).not.toContain('预览延迟')
    expect(page).toContain("props.snapshot.toolPreviewPrefs.hoverPreviewEnabled")
    expect(page).toContain("props.snapshot.toolPreviewPrefs.hoverPreviewDelayMs")
    expect(page).toContain('buildMqttPayloadPreviewSegments')
    expect(page).toContain('buildMqttInlinePayloadPreviewSegments')
    expect(page).toContain('ref="previewPayloadRef"')
    expect(page).toContain('@scroll.passive="syncPreviewScroll"')
    expect(page).toContain('mqtt-preview-payload')
    expect(page).toContain('mqtt-preview-payload-content')
    expect(page).not.toContain('transform: `translateY(-${props.snapshot.mqttPreview.scrollTop}px)`')
    expect(page).toContain('mqtt-preview-token')
    expect(page).toContain('mqtt-preview-direction')
    expect(page).toContain('mqtt-preview-topic')
    expect(page).toContain('mqtt-preview-time')
    expect(page).toContain("source: 'shift'")
    expect(page).toContain('props.shiftPreview')
    expect(page).toContain("props.snapshot.mqttPreview.source !== 'shift'")
    expect(page).toContain('mqtt-workspace-resizer')
    expect(page).toContain('resizeMqttLayout')
    expect(page).toContain('mqtt-item-payload-snippet')
    expect(page).toContain('payloadSnippetSegments(message.payload)')
    expect(page).toContain('mqtt-topic-alias-badge')
    expect(page).toContain('mqtt-message-bubble-in')
    expect(page).toContain('mqtt-message-bubble-out')
    expect(page).toContain('aria-label="新增订阅"')
    expect(page).toContain('aria-label="清空全部订阅"')
    expect(page).toContain('aria-label="发送 MQTT 消息"')
    expect(page).toContain('data-role="mqtt-search"')
    expect(page).toContain('data-role="mqtt-editor"')
    expect(page).toContain('data-role="mqtt-favorite-editor"')
    expect(page).toContain('ref="workbenchRef"')
    expect(page).toContain('data-mqtt-shortcut-hint')
    expect(page).toContain('shortcutHintEntries')
    expect(page).toContain('updateShortcutHintPositions')
    expect(page).toContain('layoutShortcutHints')
    expect(page).toContain('isVisibleShortcutHintAnchor')
    expect(page).toContain('<Teleport to="body">')
    expect(page).toContain('mqtt-shortcut-top-layer')
    expect(page).not.toContain('<kbd v-if="visibleCommandHint')
    const messageActionStart = page.indexOf('<span class="mqtt-message-actions" aria-label="消息操作">')
    const messageActionEnd = page.indexOf('</span>', messageActionStart)
    const messageActions = page.slice(messageActionStart, messageActionEnd)
    expect(messageActions).toContain('aria-label="预览消息"')
    expect(messageActions).toContain('mqtt.preview.open')
    expect(messageActions).toContain('aria-label="详情消息"')
    expect(messageActions).toContain('mqtt.detail.open')
    expect(messageActions).toContain('aria-label="快捷操作"')
    expect(messageActions).toContain('mqtt.drawer.open')
    expect(messageActions.match(/<button/g)).toHaveLength(3)
    expect(messageActions).not.toContain('复制主题')
    expect(messageActions).not.toContain('复制内容')
    expect(messageActions).not.toContain('再次发送')
    expect(messageActions).not.toContain('填入发布')
    expect(css).toContain('.mqtt-workbench-grid')
    expect(css).toContain('.mqtt-connection-rail')
    expect(css).toContain('.mqtt-subscription-rail')
    expect(css).toContain('.mqtt-message-workspace')
    expect(css).toContain('.mqtt-workspace-split')
    expect(css).toContain('.mqtt-panel-toggle')
    expect(css).toContain('.mqtt-message-row')
    expect(css).toContain('.mqtt-log-drawer')
    expect(css).toContain('.mqtt-log-detail')
    expect(css).toContain('.mqtt-subscription-row')
    expect(css).toContain('.mqtt-subscription-row.selected')
    expect(css).toContain('.mqtt-subscription-unread')
    expect(css).toContain('.mqtt-subscription-route')
    expect(css).toContain('grid-template-columns: minmax(0, 3fr) minmax(60px, 2fr)')
    expect(css).toContain('.mqtt-subscription-shortcut-popover')
    expect(css).toContain('.mqtt-subscription-delete')
    expect(css).toContain('.mqtt-subscription-row-actions')
    expect(css).toContain('.mqtt-subscription-title-line')
    expect(css).toContain('.mqtt-subscription-rail .mqtt-rail-title > .mqtt-rail-actions')
    expect(css).toContain('flex-wrap: nowrap')
    expect(css).toContain('.mqtt-subscription-list')
    expect(css).toContain('.mqtt-subscription-editor')
    expect(css).toContain('.mqtt-subscription-modal')
    expect(css).not.toContain('.mqtt-publish-record-grid')
    expect(css).toContain('.mqtt-panel-title-actions')
    expect(css).toContain('.mqtt-publish-record-list')
    expect(css).toMatch(/\.mqtt-receive-panel \{[^}]*grid-template-rows:\s*minmax\(0,\s*1fr\);/s)
    expect(css).toMatch(/\.mqtt-filter-buttons button\.active \{[^}]*background:\s*#00a676;/s)
    expect(css).toContain('.mqtt-filter-buttons button.active .mqtt-stat-count')
    expect(css).toContain('box-shadow: inset 0 0 0 1px #00a676, 0 0 0 2px rgba(0, 166, 118, 0.16)')
    expect(css).toContain('.mqtt-record-checkbox')
    expect(css).not.toContain('.mqtt-send-actions')
    expect(css).toContain('.mqtt-config-drawer')
    expect(css).toContain('.mqtt-config-drawer-overlay')
    expect(css).toContain('.mqtt-endpoint-preview')
    expect(css).toContain('.mqtt-icon-button')
    expect(css).toContain('.mqtt-collapsed-logo')
    expect(css).toContain('.mqtt-stat-count')
    expect(css).toContain('.mqtt-command-bar')
    expect(css).toContain('grid-template-columns: minmax(132px, 0.82fr) minmax(150px, 0.9fr) max-content')
    expect(css).not.toContain('.mqtt-jump-strip')
    expect(css).not.toContain('.mqtt-jump-chip')
    expect(css).toContain('.mqtt-record-mode-buttons')
    expect(css).toContain('grid-template-columns: repeat(3, 26px)')
    expect(css).toMatch(/\.mqtt-record-mode-buttons \.mqtt-filter-button \{[^}]*width:\s*26px;[^}]*min-width:\s*26px;[^}]*height:\s*26px;[^}]*padding:\s*0;/s)
    expect(css).toContain('.mqtt-record-mode-panel')
    expect(css).toContain('.mqtt-message-stream')
    expect(css).not.toContain('.mqtt-message-timeline::before')
    expect(css).toContain('.mqtt-message-bubble')
    expect(css).toContain('--mqtt-row-height: 34px')
    expect(css).toMatch(/\.mqtt-message-bubble,\s*\.mqtt-publish-record-row \{[^}]*height:\s*var\(--mqtt-row-height\);[^}]*max-height:\s*var\(--mqtt-row-height\);[^}]*overflow:\s*hidden;/s)
    expect(css).toContain('.mqtt-topic-alias-badge')
    expect(css).toContain('.mqtt-preview-layer')
    expect(css).toContain('.mqtt-preview-payload')
    expect(css).toContain('.mqtt-preview-payload-content')
    expect(css).toContain('.mqtt-preview-token-key')
    expect(css).toContain('.drawer-overlay-left')
    expect(css).toContain('.mqtt-detail-drawer')
    expect(css).toContain('.mqtt-item-payload-snippet')
    expect(css).toContain('.mqtt-message-bubble-in')
    expect(css).toContain('.mqtt-message-bubble-out')
    expect(css).toContain('width: 100%')
    expect(css).not.toContain('width: min(66.666%, 980px)')
    expect(css).toContain('.mqtt-publish-command-bar')
    expect(css).toContain('.mqtt-publish-actions')
    expect(css).toMatch(/\.mqtt-publish-actions \{[^}]*grid-template-columns:\s*repeat\(3,\s*26px\);/s)
    expect(css).not.toMatch(/\.mqtt-publish-record-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
    expect(css).not.toContain('grid-template-areas:')
    expect(css).not.toContain('"summary records"')
    expect(css).not.toContain('"filters filters"')
    expect(css).toMatch(/@media \(max-width: 1100px\) \{[\s\S]*\.mqtt-command-bar \{[\s\S]*grid-template-columns:\s*minmax\(118px,\s*0\.78fr\)\s*minmax\(132px,\s*0\.9fr\)\s*max-content;/s)
    expect(css).toMatch(/@media \(max-width: 1100px\) \{[\s\S]*\.mqtt-publish-command-bar \{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*78px\s*auto\s*max-content;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*body \{[\s\S]*min-width:\s*0;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*\.mqtt-command-bar \{[\s\S]*grid-template-columns:\s*118px\s*132px\s*82px;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*\.mqtt-command-bar \{[\s\S]*overflow-x:\s*auto;/s)
    expect(css).toMatch(/@media \(max-width: 700px\) \{[\s\S]*\.mqtt-publish-command-bar \{[\s\S]*grid-template-columns:\s*minmax\(150px,\s*1fr\)\s*76px\s*auto\s*max-content;/s)
    expect(css).toContain('.mqtt-workspace-resizer')
    expect(css).toContain('--mqtt-stack-receive-ratio')
    expect(css).toContain('--mqtt-split-receive-ratio')
    expect(css).toContain('--z-shortcut-top-layer')
    expect(css).toContain('.mqtt-shortcut-top-layer')
    expect(css).toMatch(/\.mqtt-shortcut-badge \{[^}]*position:\s*fixed;/s)
    expect(css).toMatch(/\.mqtt-shortcut-badge \{[^}]*z-index:\s*var\(--z-shortcut-top-layer\);/s)
    expect(css).toContain('position: fixed')
    expect(css).toContain('--mqtt-preview-left')
    expect(css).toContain('--mqtt-preview-top')
    expect(css).toContain('--mqtt-preview-max-height')
    expect(css).toContain('height: 100dvh')
    expect(css).toContain('.app-shell')
    expect(css).toContain('.tab-content')
    const media900Index = css.indexOf('@media (max-width: 900px)')
    const media700Index = css.indexOf('@media (max-width: 700px)')
    expect(media700Index).toBeGreaterThan(media900Index)
    expect(css.slice(media900Index, media700Index)).not.toContain('.mqtt-workbench-grid')
    const previewCss = css.slice(css.indexOf('.mqtt-preview-layer'), css.indexOf('.mqtt-preview-layer header'))
    expect(previewCss).not.toContain('right: 18px')
    expect(previewCss).not.toContain('top: 72px')
    expect(previewCss).toContain('width: var(--mqtt-preview-width, min(420px, calc(100vw - 16px)))')
    expect(previewCss).toContain('min-height: 160px')
    const previewPayloadStart = css.indexOf('.mqtt-preview-payload')
    const previewPayloadCss = css.slice(previewPayloadStart, css.indexOf('.mqtt-preview-token', previewPayloadStart))
    expect(previewPayloadCss).toContain('overflow: auto')
    expect(previewPayloadCss).toContain('font-size: 12px')
    expect(previewPayloadCss).not.toContain('transition: transform')
  })
})
