import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('settings layout', () => {
  it('uses scoped settings sub tabs and passes app settings for maintenance display', () => {
    const app = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')
    const settingsPage = readFileSync(resolve(process.cwd(), 'src/pages/SettingsPage.vue'), 'utf8')

    expect(settingsPage).toContain("type SettingsTabId = 'shortcuts' | 'maintenance'")
    expect(settingsPage).toContain('settingsTabId')
    expect(settingsPage).toContain('settings-sub-tabs')
    expect(settingsPage).toContain("id: 'maintenance', label: '维护'")
    expect(app).toContain(':settings="snapshot.state.settings"')
  })

  it('keeps shortcuts in a single-column compact worktable without the old right inspector', () => {
    const settingsPage = readFileSync(resolve(process.cwd(), 'src/pages/SettingsPage.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')

    expect(settingsPage).toContain('shortcut-strip')
    expect(settingsPage).toContain('shortcut-compact-row')
    expect(settingsPage).toContain('primaryShortcutRows')
    expect(settingsPage).toContain('maintenanceShortcutRows')
    expect(settingsPage).toContain('commandTooltip(row)')
    expect(settingsPage).toContain('scopeDisplay(row)')
    expect(settingsPage).toContain('stateDisplay(row)')
    expect(settingsPage).toContain('{{ row.commandId }}')
    expect(settingsPage).toContain('shortcut-command-tooltip')
    expect(settingsPage).toContain('shortcutCommandTooltipTitle(row)')
    expect(settingsPage).toContain('settings-shortcut-search-wrap')
    expect(settingsPage).toContain('settings-search-shortcut-hint')
    expect(settingsPage).toContain('shortcutModifierHinting')
    expect(settingsPage).toContain('@mousemove="updateCommandTooltipPosition"')
    expect(settingsPage).toContain('commandTooltipLines(row).slice(1)')
    expect(settingsPage).not.toContain('<small>{{ row.title }}</small>')
    expect(settingsPage).toContain('data-role="settings-shortcut-search"')
    expect(settingsPage).toContain('handleSettingsKeydown')
    expect(settingsPage).toContain('handleSettingsKeyup')
    expect(settingsPage).not.toContain('<small>默认 {{ formatShortcutList(row.defaultShortcutIds) || \'无\' }}</small>')
    expect(settingsPage).not.toContain('class="shortcut-preview-strip"')
    expect(settingsPage).not.toContain('shortcut-inspector')
    expect(css).toMatch(/\.shortcut-settings-layout \{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\);/s)
    expect(css).toMatch(/\.shortcut-compact-row \{[^}]*grid-template-columns:/s)
    expect(css).toContain('.command-tooltip-trigger')
    expect(css).toContain('.shortcut-command-tooltip')
    expect(css).toContain('.command-cell:hover .shortcut-command-tooltip')
    expect(css).toMatch(/\.command-cell \{[^}]*align-self:\s*stretch;/s)
    expect(css).toContain('.settings-search-shortcut-hint')
    expect(css).toContain('.settings-shortcut-search-wrap.hinting .settings-search-shortcut-hint')
    expect(css).toMatch(/\.settings-search-shortcut-hint \{[^}]*opacity:\s*0;[^}]*visibility:\s*hidden;/s)
    expect(css).toMatch(/\.shortcut-command-tooltip \{[^}]*position:\s*fixed;[^}]*left:\s*var\(--shortcut-tooltip-x, 0px\);[^}]*top:\s*var\(--shortcut-tooltip-y, 0px\);/s)
    expect(css).toMatch(/\.shortcut-command-tooltip \{[^}]*transform:\s*translateY\(-100%\);/s)
    expect(css).toMatch(/\.shortcut-command-tooltip \{[^}]*transition-delay:\s*0ms;/s)
    expect(css).toMatch(/\.command-cell:hover \.shortcut-command-tooltip \{[^}]*transition-delay:\s*var\(--mouse-tooltip-delay\);/s)
    expect(css).toContain('width: max-content;')
    expect(css).not.toContain('shortcut-command-drawer')
    expect(css).not.toContain('.shortcut-compact-row.selected .shortcut-command-tooltip')
    expect(css).not.toContain('.shortcut-compact-row:focus-within .shortcut-command-tooltip')
    expect(css).toContain('.maintenance-command-table')
    expect(css).toContain('.maintenance-preview-strip')
    expect(css).not.toContain('.shortcut-inspector')
  })

  it('uses EzClipboard-style shortcut record management with draft save controls', () => {
    const settingsPage = readFileSync(resolve(process.cwd(), 'src/pages/SettingsPage.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')

    expect(settingsPage).toContain('draftShortcutProfiles')
    expect(settingsPage).toContain('shortcutDraftDirty')
    expect(settingsPage).toContain('saveShortcutProfiles')
    expect(settingsPage).toContain('saveShortcutDraft')
    expect(settingsPage).toContain('isConfirmSaveShortcut')
    expect(settingsPage).toContain('discardShortcutDraft')
    expect(settingsPage).toContain('shortcut-draft-actions')
    expect(settingsPage).toContain('shortcutRecordActiveIds')
    expect(settingsPage).toContain('shortcutRecordPendingIds')
    expect(settingsPage).toContain('shortcutRecordCapturedId')
    expect(settingsPage).toContain('shortcutRecordDirectInput')
    expect(settingsPage).toContain('shortcutRecordEditingIndex')
    expect(settingsPage).toContain('promoteShortcutRecordCaptured')
    expect(settingsPage).toContain('restoreShortcutRecordToDefault')
    expect(settingsPage).toContain('requestCloseRecord')
    expect(settingsPage).toContain('confirmDiscardMessage')
    expect(settingsPage).toContain('当前绑定')
    expect(settingsPage).toContain('待绑定')
    expect(settingsPage).toContain('按下快捷键录制')
    expect(settingsPage).toContain('或直接录入')
    expect(settingsPage).toContain('恢复默认')
    expect(settingsPage).not.toContain('recordDraft')
    expect(settingsPage).not.toContain('@input="updateRecordDraft"')
    expect(css).toContain('.shortcut-record-head')
    expect(css).toContain('.shortcut-record-panels')
    expect(css).toContain('.shortcut-record-panel--current')
    expect(css).toContain('.shortcut-record-capture-row')
    expect(css).toContain('.shortcut-record-direct-input-row')
    expect(css).toContain('.shortcut-record-default-reset')
    expect(settingsPage).toContain('shortcut-record-modal')
    expect(settingsPage).toContain('shortcut-record-scroll')
    expect(settingsPage).toContain('shortcut-record-actions')
    expect(settingsPage).toContain('<span class="confirm-actions shortcut-record-actions">')
    expect(settingsPage).not.toContain('<button type="button" @click="requestCloseRecord">关闭</button>')
    expect(settingsPage).not.toContain('<footer class="confirm-actions shortcut-record-actions">')
    expect(css).toMatch(/\.shortcut-record-scroll \{[^}]*overflow-y:\s*auto;/s)
    expect(css).toMatch(/\.shortcut-record-modal \{[^}]*max-height:\s*calc\(100vh - 48px\);/s)
    expect(css).toMatch(/\.shortcut-record-panels \{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/s)
    expect(css).not.toContain('width: min(700px, calc(100vw - 32px));')
    expect(css).not.toContain('.shortcut-record-actions {')
    expect(css).not.toMatch(/@media \(max-width: 900px\)[\s\S]*\.shortcut-record-panels \{[\s\S]*grid-template-columns:\s*1fr;/)
  })

  it('moves layer and storage configuration into the maintenance tab', () => {
    const settingsPage = readFileSync(resolve(process.cwd(), 'src/pages/SettingsPage.vue'), 'utf8')
    const css = readFileSync(resolve(process.cwd(), 'src/styles/app.css'), 'utf8')

    expect(settingsPage).toContain('settings-maintenance')
    expect(settingsPage).toContain("type MaintenanceSectionId = 'features' | 'layers' | 'storage' | 'commands' | 'resolution' | 'reservations'")
    expect(settingsPage).toContain('maintenanceSectionId')
    expect(settingsPage).toContain('maintenance-section-nav')
    expect(settingsPage).toContain('maintenance-center')
    expect(settingsPage).toContain('maintenance-panel-body')
    expect(settingsPage).toContain('maintenance-feature-body')
    expect(settingsPage).toContain('功能开关')
    expect(settingsPage).toContain('featureRows')
    expect(settingsPage).toContain('saveFeatureDraft')
    expect(settingsPage).toContain('onFeatureDrop')
    expect(settingsPage).toContain('draggingFeatureId')
    expect(settingsPage).toContain('maintenance-layer-body')
    expect(settingsPage).toContain('maintenance-storage-body')
    expect(settingsPage).toContain('maintenance-command-table')
    expect(settingsPage).toContain('层级优先级')
    expect(settingsPage).toContain('保留键与接管层')
    expect(settingsPage).toContain('当前存储')
    expect(settingsPage).toContain('SQLite')
    expect(settingsPage).toContain('Layer Commands')
    expect(settingsPage).toContain('ports.detail.close')
    expect(settingsPage).toContain('props.settings.preferSqlite')
    expect(settingsPage).not.toContain("maintenanceSectionId === 'overview'")
    expect(settingsPage).not.toContain('maintenance-overview')
    expect(settingsPage).not.toContain('maintenance-grid')
    expect(css).toMatch(/\.settings-maintenance \{[^}]*grid-template-columns:\s*176px minmax\(0,\s*1fr\);/s)
    expect(css).toContain('.maintenance-center')
    expect(css).toContain('.maintenance-section-nav')
    expect(css).toContain('.maintenance-feature-body')
    expect(css).toContain('.feature-config-row')
    expect(css).toContain('.maintenance-command-table')
    expect(css).toMatch(/\.maintenance-panel-body \{[^}]*overflow:\s*auto;/s)
    expect(css).not.toContain('.maintenance-grid')
  })
})
