import type { FeatureActionHostV7 } from '../featureActionHost'

export function registerFavoritesActions(host: FeatureActionHostV7): void {
  const { register, activateFavoriteSlot, addSelectedDirectoryEntries, applyFocusedFavoriteContainer, applySuggestedFavoriteRunner, assignFavoriteSlot, beginFavoriteDraft, blurSearchFocus, cancelFavoritePickReview, cancelFavoriteRunPrompt, clearFavoriteSlot, closeFavoriteDrawer, closeFavoriteSlotManager, commitFavoritePickReview, configureFavoriteSlotHotkey, copyDirectoryTargetPaths, copyFavoriteItems, copyFavoritePath, copyFavoriteRunCommand, copyFavoriteRunLogPath, cycleFavoriteDraftField, cycleFavoritePane, cycleFavoritePickReview, directoryPathsFromArgs, executeFavoriteDrawerItem, executeQuickFavoriteAt, favoriteActionTargetKind, favoriteIdFromArgs, favoritePickKindFromArgs, focusDuplicateFavorite, focusFavoriteActionTarget, focusFavoriteGroupSearch, focusFavoriteSearch, loadSelectedFavoriteDirectory, moveFavoriteDrawer, notify, openDirectoryTargets, openFavorite, openFavoriteDrawer, openFavoriteRunLog, openFavoriteSlotManager, pickFavoriteDraftPath, pickFavoritesForReview, refreshFavoritePathInspections, removeFavorite, removeFavoriteNow, reorderFavoriteMetadata, resetFavoriteLearning, revealDirectoryTargets, revealFavorite, revealFavoriteRunLog, save, saveFavoriteDraft, selectedFavoriteMetadataIds, submitFavoriteRunPrompt, undoFavoriteRemoval } = host
    register({ id: 'favorites.pane.toggleNext', title: '切换收藏栏', group: '收藏', risk: 'normal', scope: 'tab', priority: 100, shortcut: 'Tab', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: () => cycleFavoritePane(1) })
    register({ id: 'favorites.pane.togglePrev', title: '反向切换收藏栏', group: '收藏', risk: 'normal', scope: 'tab', priority: 100, shortcut: 'Shift+Tab', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: () => cycleFavoritePane(-1) })
    register({ id: 'favorites.search.focus', title: '聚焦收藏搜索', group: '收藏', risk: 'normal', scope: 'tab', priority: 99, shortcut: 'Ctrl+F', when: (ctx) => ctx.tab === 'favorites', run: () => focusFavoriteSearch() })
    register({ id: 'favorites.groupSearch.focus', title: '聚焦收藏分组搜索', group: '收藏', risk: 'normal', scope: 'tab', priority: 99, shortcut: 'Ctrl+Shift+F', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: () => focusFavoriteGroupSearch() })
    register({ id: 'favorites.group.apply', title: '应用收藏容器', group: '收藏', risk: 'normal', scope: 'tab', priority: 100, shortcut: 'Enter', when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => applyFocusedFavoriteContainer(favoriteIdFromArgs(args) || host.focusedFavoriteGroupId) })
    register({ id: 'favorites.target.create', title: '新增收藏目标', group: '收藏', risk: 'data-write', scope: 'tab', priority: 95, shortcut: 'Ctrl+N', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => { if (favoriteIdFromArgs(args)) focusFavoriteActionTarget(args, true); host.favoriteAddMenuOpen = false; return beginFavoriteDraft('create-target') } })
    register({ id: 'favorites.group.create', title: '新增收藏分组', group: '收藏', risk: 'data-write', scope: 'tab', priority: 95, shortcut: 'Ctrl+G', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => { if (favoriteIdFromArgs(args)) focusFavoriteActionTarget(args, true); host.favoriteAddMenuOpen = false; return beginFavoriteDraft('create-group') } })
    register({ id: 'favorites.group.moveParent', title: '移动收藏父级', group: '收藏', risk: 'data-write', scope: 'tab', priority: 95, shortcut: 'Ctrl+F2', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => beginFavoriteDraft('move-parent', args) })
    register({ id: 'favorites.group.collapse', title: '折叠收藏分组', group: '收藏', risk: 'normal', scope: 'tab', priority: 95, shortcut: 'ArrowLeft', when: (ctx) => ctx.tab === 'favorites', run: () => { if (!host.focusedFavoriteGroupId) return false; host.state.collapsedFavoriteGroupIds = [...new Set([...host.state.collapsedFavoriteGroupIds, host.focusedFavoriteGroupId])]; save(); notify(); return true } })
    register({ id: 'favorites.group.expand', title: '展开收藏分组', group: '收藏', risk: 'normal', scope: 'tab', priority: 95, shortcut: 'ArrowRight', when: (ctx) => ctx.tab === 'favorites', run: () => { if (!host.focusedFavoriteGroupId) return false; host.state.collapsedFavoriteGroupIds = host.state.collapsedFavoriteGroupIds.filter((id: string) => id !== host.focusedFavoriteGroupId); save(); notify(); return true } })
    register({ id: 'favorites.open', title: '打开或运行收藏', group: '收藏', risk: 'normal', scope: 'tab', priority: 100, shortcut: 'Enter', when: (ctx) => ctx.tab === 'favorites' && (host.favoriteCapabilities.open || host.favoriteCapabilities.run === true), run: (_ctx, args) => { if (favoriteActionTargetKind(args) === 'directory') void openDirectoryTargets(directoryPathsFromArgs(args)); else void openFavorite(args); return true } })
    register({ id: 'favorites.reveal', title: '定位收藏', group: '收藏', risk: 'normal', scope: 'tab', priority: 100, shortcut: 'Ctrl+Enter', when: (ctx) => ctx.tab === 'favorites' && host.favoriteCapabilities.reveal, run: (_ctx, args) => { if (favoriteActionTargetKind(args) === 'directory') void revealDirectoryTargets(directoryPathsFromArgs(args)); else void revealFavorite(args); return true } })
    register({ id: 'favorites.copyPath', title: '复制收藏路径', group: '收藏', risk: 'normal', scope: 'tab', priority: 95, when: (ctx) => ctx.tab === 'favorites' && host.favoriteCapabilities.copyPath, run: (_ctx, args) => { if (favoriteActionTargetKind(args) === 'directory') void copyDirectoryTargetPaths(directoryPathsFromArgs(args)); else void copyFavoritePath(args); return true } })
    register({ id: 'favorites.copyItems', title: '复制真实文件或文件夹', group: '收藏', risk: 'normal', scope: 'tab', priority: 95, shortcut: 'Ctrl+Shift+C', when: (ctx) => ctx.tab === 'favorites' && Boolean(host.platform.files.capabilities?.copyItems), run: (_ctx, args) => { void copyFavoriteItems(args); return true } })
    register({ id: 'favorites.pick.files', title: '选择文件并审核收藏', group: '收藏', risk: 'data-write', scope: 'tab', priority: 95, shortcut: 'Ctrl+O', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode && host.favoriteCapabilities.pickFiles, run: () => { host.favoriteAddMenuOpen = false; void pickFavoritesForReview('file'); return true } })
    register({ id: 'favorites.pick.folders', title: '选择文件夹并审核收藏', group: '收藏', risk: 'data-write', scope: 'tab', priority: 94, shortcut: 'Ctrl+Shift+O', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode && host.favoriteCapabilities.pickFolders, run: () => { host.favoriteAddMenuOpen = false; void pickFavoritesForReview('folder'); return true } })
    register({ id: 'favorites.draft.pickPath', title: '为收藏草稿选择路径', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-editor'), run: (_ctx, args) => { void pickFavoriteDraftPath(favoritePickKindFromArgs(args)); return true } })
    register({ id: 'favorites.runner.applySuggestion', title: '填入常见脚本运行器建议', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-editor'), run: () => applySuggestedFavoriteRunner() })
    register({ id: 'favorites.add.duplicateFocus', title: '定位重复收藏', group: '收藏', risk: 'normal', scope: 'tab', priority: 80, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => focusDuplicateFavorite(typeof args?.id === 'string' ? args.id : null) })
    register({ id: 'favorites.remove', title: '移出收藏', group: '收藏', risk: 'data-write', scope: 'tab', priority: 100, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => removeFavorite(selectedFavoriteMetadataIds(args)) })
    register({ id: 'favorites.remove.force', title: '直接移出收藏元数据', group: '收藏', risk: 'destructive', scope: 'tab', priority: 100, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => removeFavoriteNow(selectedFavoriteMetadataIds(args)) })
    register({ id: 'favorites.reorder', title: '调整收藏顺序', group: '收藏', risk: 'data-write', scope: 'row', priority: 100, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => reorderFavoriteMetadata(String(args?.nodeId || ''), typeof args?.parentId === 'string' ? args.parentId : null, typeof args?.beforeNodeId === 'string' ? args.beforeNodeId : null) })
    register({ id: 'favorites.remove.undo', title: '撤销移出收藏', group: '收藏', risk: 'data-write', scope: 'tab', priority: 101, shortcut: 'Ctrl+Z', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode && Boolean(host.favoriteRemovalUndo?.removed.length), run: () => undoFavoriteRemoval() })
    register({ id: 'favorites.edit', title: '编辑收藏', group: '收藏', risk: 'data-write', scope: 'tab', priority: 95, shortcut: 'F2', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => beginFavoriteDraft('edit', args) })
    register({ id: 'favorites.rename', title: '重命名收藏', group: '收藏', risk: 'data-write', scope: 'tab', priority: 95, shortcut: 'Shift+F2', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => beginFavoriteDraft('rename', args) })
    register({ id: 'favorites.refresh', title: '刷新目录和路径状态', group: '收藏', risk: 'normal', scope: 'tab', priority: 96, shortcut: 'Ctrl+R', when: (ctx) => ctx.tab === 'favorites', run: () => { void loadSelectedFavoriteDirectory(); void refreshFavoritePathInspections(); return true } })
    register({ id: 'favorites.containers.togglePanel', title: '展开或收起收藏容器栏', group: '收藏', risk: 'normal', scope: 'tab', priority: 96, shortcut: 'Ctrl+Shift+W', when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: () => { host.favoriteContainerPanelOpen = !host.favoriteContainerPanelOpen; host.activeFavoritePane = host.favoriteContainerPanelOpen ? 'containers' : 'items'; notify(); return true } })
    register({ id: 'favorites.addMenu.toggle', title: '打开或关闭添加菜单', group: '收藏', risk: 'normal', scope: 'tab', priority: 96, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: () => { host.favoriteAddMenuOpen = !host.favoriteAddMenuOpen; notify(); return true } })
    register({ id: 'favorites.addMenu.close', title: '关闭添加菜单', group: '收藏', risk: 'normal', scope: 'layer', priority: 97, when: (ctx) => ctx.tab === 'favorites', run: () => { host.favoriteAddMenuOpen = false; notify(); return true } })
    register({ id: 'favorites.save', title: '保存收藏编辑', group: '收藏', risk: 'data-write', scope: 'layer', priority: 100, shortcut: 'Ctrl+S', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-editor'), run: () => saveFavoriteDraft() })
    register({ id: 'favorites.edit.nextField', title: '收藏编辑下一个字段', group: '收藏', risk: 'normal', scope: 'layer', priority: 100, shortcut: 'Tab', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-editor'), run: () => cycleFavoriteDraftField(1) })
    register({ id: 'favorites.edit.prevField', title: '收藏编辑上一个字段', group: '收藏', risk: 'normal', scope: 'layer', priority: 100, shortcut: 'Shift+Tab', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-editor'), run: () => cycleFavoriteDraftField(-1) })
    register({ id: 'favorites.cancel', title: '取消收藏编辑', group: '收藏', risk: 'normal', scope: 'layer', priority: 100, shortcut: 'Escape', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-editor'), run: () => { host.favoriteDraft = null; notify(); return true } })
    register({ id: 'favorites.slot.manager.open', title: '打开文件槽管理器', group: '收藏', risk: 'normal', scope: 'tab', priority: 96, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => openFavoriteSlotManager(args) })
    register({ id: 'favorites.slot.manager.close', title: '关闭文件槽管理器', group: '收藏', risk: 'normal', scope: 'layer', priority: 101, shortcut: 'Escape', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-slot-manager'), run: () => closeFavoriteSlotManager() })
    register({ id: 'favorites.run.prompt.submit', title: '确认运行参数', group: '收藏', risk: 'normal', scope: 'layer', priority: 103, shortcut: 'Ctrl+Enter', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-run-prompt'), run: () => submitFavoriteRunPrompt() })
    register({ id: 'favorites.run.prompt.cancel', title: '取消本次运行', group: '收藏', risk: 'normal', scope: 'layer', priority: 103, shortcut: 'Escape', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-run-prompt'), run: () => cancelFavoriteRunPrompt() })
    register({ id: 'favorites.run.openLog', title: '打开运行日志', group: '收藏', risk: 'normal', scope: 'row', priority: 93, when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => { void openFavoriteRunLog(args); return true } })
    register({ id: 'favorites.run.revealLog', title: '定位运行日志', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => { void revealFavoriteRunLog(args); return true } })
    register({ id: 'favorites.run.copyLogPath', title: '复制运行日志路径', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => { void copyFavoriteRunLogPath(args); return true } })
    register({ id: 'favorites.run.openDeclaredLog', title: '打开脚本自身日志', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => { void openFavoriteRunLog({ ...(args || {}), declared: true }); return true } })
    register({ id: 'favorites.run.copyCommand', title: '复制实际执行的命令行', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => { void copyFavoriteRunCommand(args); return true } })
    register({ id: 'favorites.learning.reset', title: '重置全部收藏搜索学习', group: '收藏', risk: 'data-write', scope: 'tab', priority: 91, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: () => resetFavoriteLearning() })
    register({ id: 'favorites.learning.resetItem', title: '重置当前收藏搜索学习', group: '收藏', risk: 'data-write', scope: 'row', priority: 91, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => resetFavoriteLearning(args) })
    for (let slot = 1; slot <= 10; slot += 1) {
      register({ id: `favorites.slot.assign.${slot}`, title: `分配到文件槽 ${slot}`, group: '收藏', risk: 'data-write', scope: 'layer', priority: 90, when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-slot-manager'), run: (_ctx, args) => assignFavoriteSlot(slot, args) })
      register({ id: `favorites.slot.clear.${slot}`, title: `清除文件槽 ${slot}`, group: '收藏', risk: 'data-write', scope: 'layer', priority: 89, when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-slot-manager'), run: () => clearFavoriteSlot(slot) })
      register({ id: `favorites.slot.test.${slot}`, title: `测试文件槽 ${slot}`, group: '收藏', risk: 'normal', scope: 'layer', priority: 88, when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-slot-manager'), run: () => { void activateFavoriteSlot(slot); return true } })
      register({ id: `favorites.slot.hotkey.${slot}`, title: `配置文件槽 ${slot} 全局快捷键`, group: '收藏', risk: 'normal', scope: 'layer', priority: 87, when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-slot-manager'), run: () => configureFavoriteSlotHotkey(slot) })
      register({ id: `favorites.slot.activate.${slot}`, title: `执行文件槽 ${slot}`, group: '收藏', risk: 'normal', scope: 'global', priority: 102, when: () => true, run: () => { void activateFavoriteSlot(slot); return true } })
      const numberShortcut = slot === 10 ? 'Ctrl+0' : `Ctrl+${slot}`
      register({ id: `favorites.quick.open.${slot}`, title: `打开快速收藏第 ${slot} 项`, group: '收藏', risk: 'normal', scope: 'tab', priority: 100 - slot, shortcut: numberShortcut, when: (ctx) => ctx.tab === 'favorites' && ctx.favoriteQuickMode === true && !ctx.layerIds.includes('favorites-drawer'), run: () => { void executeQuickFavoriteAt(slot - 1); return true } })
    }
    register({ id: 'favorites.pickReview.commit', title: '保存点选收藏', group: '收藏', risk: 'data-write', scope: 'layer', priority: 100, shortcut: 'Ctrl+S', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-pick-review'), run: () => commitFavoritePickReview() })
    register({ id: 'favorites.pickReview.cancel', title: '取消点选收藏', group: '收藏', risk: 'normal', scope: 'layer', priority: 100, shortcut: 'Escape', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-pick-review'), run: () => cancelFavoritePickReview() })
    register({ id: 'favorites.pickReview.next', title: '点选审核下一个项目', group: '收藏', risk: 'normal', scope: 'layer', priority: 100, shortcut: 'Tab', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-pick-review'), run: () => cycleFavoritePickReview(1) })
    register({ id: 'favorites.pickReview.prev', title: '点选审核上一个项目', group: '收藏', risk: 'normal', scope: 'layer', priority: 100, shortcut: 'Shift+Tab', when: (ctx) => ctx.tab === 'favorites' && ctx.layerIds.includes('favorites-pick-review'), run: () => cycleFavoritePickReview(-1) })
    register({ id: 'favorites.search.blur', title: '退出收藏搜索焦点', group: '收藏', risk: 'normal', scope: 'layer', priority: 99, shortcut: 'Escape', when: (ctx) => ctx.tab === 'favorites', run: () => blurSearchFocus() })
    register({ id: 'favorites.detail.open', title: '打开收藏详情', description: '展示当前收藏节点或实际目录项详情。', icon: 'detail', group: '收藏', risk: 'normal', scope: 'tab', priority: 96, shortcut: 'Ctrl+ArrowLeft', when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => openFavoriteDrawer(false, args) })
    register({ id: 'favorites.detail.close', title: '关闭收藏详情', description: '关闭左侧收藏详情面板。', icon: 'close', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites', run: () => closeFavoriteDrawer() })
    register({ id: 'favorites.drawer.open', title: '打开收藏动作抽屉', description: '展示当前收藏节点或实际目录行可执行动作。', icon: 'drawer', group: '收藏', risk: 'normal', scope: 'tab', priority: 96, shortcut: 'Ctrl+ArrowRight', when: (ctx) => ctx.tab === 'favorites', run: (_ctx, args) => openFavoriteDrawer(true, args) })
    register({ id: 'favorites.drawer.close', title: '关闭收藏动作抽屉', description: '关闭右侧收藏动作抽屉。', icon: 'close', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites', run: () => closeFavoriteDrawer() })
    register({ id: 'favorites.drawer.next', title: '收藏抽屉下移', description: '移动到下一个收藏抽屉动作。', icon: 'down', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites', run: () => moveFavoriteDrawer(1) })
    register({ id: 'favorites.drawer.prev', title: '收藏抽屉上移', description: '移动到上一个收藏抽屉动作。', icon: 'up', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites', run: () => moveFavoriteDrawer(-1) })
    register({ id: 'favorites.drawer.select', title: '执行收藏抽屉动作', description: '执行当前高亮的收藏抽屉动作。', icon: 'enter', group: '收藏', risk: 'normal', scope: 'layer', priority: 96, when: (ctx) => ctx.tab === 'favorites', run: () => executeFavoriteDrawerItem() })
    register({ id: 'favorites.directory.open', title: '打开实际目录项', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode && host.favoriteCapabilities.open, run: (_ctx, args) => { void openDirectoryTargets(directoryPathsFromArgs(args)); return true } })
    register({ id: 'favorites.directory.reveal', title: '定位实际目录项', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode && host.favoriteCapabilities.reveal, run: (_ctx, args) => { void revealDirectoryTargets(directoryPathsFromArgs(args)); return true } })
    register({ id: 'favorites.directory.copyPath', title: '复制实际目录项路径', group: '收藏', risk: 'normal', scope: 'row', priority: 92, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode && host.favoriteCapabilities.copyPath, run: (_ctx, args) => { void copyDirectoryTargetPaths(directoryPathsFromArgs(args)); return true } })
    register({ id: 'favorites.directory.addSelected', title: '添加实际目录项到收藏', group: '收藏', risk: 'data-write', scope: 'row', priority: 91, when: (ctx) => ctx.tab === 'favorites' && !ctx.favoriteQuickMode, run: (_ctx, args) => addSelectedDirectoryEntries(directoryPathsFromArgs(args)) })
    for (let index = 1; index <= 10; index += 1) {
      register({
        id: `favorites.drawer.select.${index}`,
        title: `执行收藏抽屉第 ${index} 个动作`,
        description: '执行右侧收藏抽屉中的指定序号动作。',
        icon: 'number',
        group: '收藏',
        risk: 'normal',
        scope: 'layer',
        priority: 90 - index,
        shortcut: index === 10 ? 'Ctrl+0' : `Ctrl+${index}`,
        when: (ctx) => ctx.tab === 'favorites',
        run: () => executeFavoriteDrawerItem(index - 1)
      })
    }
}
