import type { ShortcutCommandProfileConfig } from '../../keybinding/commandProfile'

export const PORTS_COMMAND_PROFILES = {
  'ports.workspace.reset': { title: '重置端口工作区', group: '端口', layer: 'ports', shortcutIds: ['Escape'], when: "tab == 'ports'", weight: 90 },
  'ports.selection.clear': { title: '清空端口多选', group: '端口', layer: 'ports-selection', shortcutIds: ['Escape'], when: "tab == 'ports' && portSelectionMode", weight: 300 },
  'ports.kill.confirm': { title: '终止选中进程', group: '端口', layer: 'ports', shortcutIds: ['Delete', 'Backspace'], when: "tab == 'ports' && portPane != 'groups' && !textInputFocused", weight: 120, risk: 'data-write' },
  'ports.kill.force': { title: '强杀选中进程', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Delete', 'Ctrl+Backspace'], when: "tab == 'ports' && portPane != 'groups' && (!textInputFocused || activeInputRole == 'port-search')", weight: 120, risk: 'destructive' },
  'ports.scan': { title: '刷新端口', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+R'], when: "tab == 'ports'", weight: 100 },
  'ports.groups.togglePanel': { title: '展开/收起端口组栏', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Shift+W'], when: "tab == 'ports' && !confirmOpen && (!textInputFocused || activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 135 },
  'ports.search.focus': { title: '聚焦端口搜索', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+F'], when: "tab == 'ports' && !confirmOpen", weight: 140 },
  'ports.groupSearch.focus': { title: '聚焦端口组搜索', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Shift+F'], when: "tab == 'ports' && !confirmOpen", weight: 140 },
  'ports.search.blur': { title: '退出端口搜索焦点', group: '端口', layer: 'ports-search', shortcutIds: ['Escape'], when: "tab == 'ports' && (activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 500 },
  'ports.pane.toggleNext': { title: '切换端口栏', group: '端口', layer: 'ports', shortcutIds: ['Tab'], when: "tab == 'ports' && (!textInputFocused || activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 130 },
  'ports.pane.togglePrev': { title: '反向切换端口栏', group: '端口', layer: 'ports', shortcutIds: ['Shift+Tab'], when: "tab == 'ports' && (!textInputFocused || activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 130 },
  'ports.pane.groups': { title: '聚焦端口组栏', group: '端口', layer: 'ports', shortcutIds: ['Alt+ArrowLeft'], when: "tab == 'ports' && !textInputFocused", weight: 110 },
  'ports.pane.results': { title: '聚焦端口结果栏', group: '端口', layer: 'ports', shortcutIds: ['Alt+ArrowRight'], when: "tab == 'ports' && !textInputFocused", weight: 110 },
  'ports.group.edit.cancel': { title: '取消端口组编辑', group: '端口', layer: 'port-group-editor', shortcutIds: ['Escape'], when: "tab == 'ports' && activeInputRole == 'port-group-editor'", weight: 400 },
  'ports.group.save': { title: '保存端口组编辑', group: '端口', layer: 'port-group-editor', shortcutIds: ['Ctrl+S', 'Ctrl+Enter'], when: "tab == 'ports' && activeInputRole == 'port-group-editor'", weight: 400, risk: 'data-write' },
  'ports.group.edit.nextField': { title: '编辑层下一个字段', group: '端口', layer: 'port-group-editor', shortcutIds: ['Tab'], when: "tab == 'ports' && activeInputRole == 'port-group-editor'", weight: 400 },
  'ports.group.edit.prevField': { title: '编辑层上一个字段', group: '端口', layer: 'port-group-editor', shortcutIds: ['Shift+Tab'], when: "tab == 'ports' && activeInputRole == 'port-group-editor'", weight: 400 },
  'ports.group.apply': { title: '应用端口组过滤', group: '端口', layer: 'ports', shortcutIds: ['Enter'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130 },
  'ports.group.focusMatches': { title: '聚焦组内端口', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Enter'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 131 },
  'ports.group.kill.confirm': { title: '终止当前端口组', group: '端口', layer: 'ports', shortcutIds: ['Shift+Enter'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'data-write' },
  'ports.group.kill.force': { title: '强杀当前端口组', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Shift+Enter'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'destructive' },
  'ports.group.rename': { title: '重命名端口组', group: '端口', layer: 'ports', shortcutIds: ['Shift+F2'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'data-write' },
  'ports.group.moveFolder': { title: '变更端口组分组夹', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+F2'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'data-write' },
  'ports.group.edit': { title: '编辑端口组', group: '端口', layer: 'ports', shortcutIds: ['F2', 'Ctrl+E'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'data-write' },
  'ports.group.delete': { title: '删除端口组/夹', group: '端口', layer: 'ports', shortcutIds: ['Delete', 'Backspace'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'data-write' },
  'ports.group.delete.force': { title: '强制删除端口组/夹', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Delete', 'Ctrl+Backspace'], when: "tab == 'ports' && portPane == 'groups' && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 130, risk: 'destructive' },
  'ports.groupFolder.create': { title: '新增分组夹', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+T'], when: "tab == 'ports' && (!textInputFocused || activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 129, risk: 'data-write' },
  'ports.group.createFromSelection': { title: '选中端口收藏为组', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+G'], when: "tab == 'ports' && (!textInputFocused || activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 120, risk: 'data-write' },
  'ports.groupTarget.toggle': { title: '折叠/展开端口组夹', group: '端口', layer: 'ports', shortcutIds: [], when: "tab == 'ports' && portPane == 'groups' && !portDrawerActive && !portGroupDetailActive && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 132 },
  'ports.groupTarget.collapse': { title: '折叠端口组夹', group: '端口', layer: 'ports', shortcutIds: ['ArrowLeft'], when: "tab == 'ports' && portPane == 'groups' && !portDrawerActive && !portGroupDetailActive && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 132 },
  'ports.groupTarget.expand': { title: '展开端口组夹', group: '端口', layer: 'ports', shortcutIds: ['ArrowRight'], when: "tab == 'ports' && portPane == 'groups' && !portDrawerActive && !portGroupDetailActive && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 132 },
  'ports.groupDetail.open': { title: '打开端口组详情抽屉', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+ArrowLeft'], when: "tab == 'ports' && portPane == 'groups' && !confirmOpen && !portGroupDetailActive && (!textInputFocused || activeInputRole == 'port-group-search')", weight: 131 },
  'ports.groupDetail.close': { title: '关闭端口组详情抽屉', group: '端口', layer: 'port-group-detail', shortcutIds: ['ArrowRight', 'Escape'], when: "tab == 'ports' && portGroupDetailActive", weight: 400 },
  'ports.drawer.open': { title: '打开端口动作抽屉', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+ArrowRight'], when: "tab == 'ports' && !confirmOpen && !portDrawerActive && (!textInputFocused || activeInputRole == 'port-search' || activeInputRole == 'port-group-search')", weight: 130 },
  'ports.drawer.close': { title: '关闭端口动作抽屉', group: '端口', layer: 'port-drawer', shortcutIds: ['ArrowLeft', 'Escape'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.detail.open': { title: '打开端口详情抽屉', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+ArrowLeft'], when: "tab == 'ports' && portPane != 'groups' && !confirmOpen && !portDetailActive && (!textInputFocused || activeInputRole == 'port-search')", weight: 130 },
  'ports.detail.close': { title: '关闭端口详情抽屉', group: '端口', layer: 'port-detail', shortcutIds: ['ArrowRight', 'Escape'], when: "tab == 'ports' && portDetailActive", weight: 400 },
  'ports.drawer.next': { title: '抽屉内下移', group: '端口', layer: 'port-drawer', shortcutIds: ['ArrowDown', 'Ctrl+J'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.prev': { title: '抽屉内上移', group: '端口', layer: 'port-drawer', shortcutIds: ['ArrowUp', 'Ctrl+K'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.select': { title: '执行抽屉当前动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Enter'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.select.1': { title: '执行抽屉第 1 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+1'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.1': { title: '直接执行第 1 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+1'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.2': { title: '执行抽屉第 2 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+2'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.2': { title: '直接执行第 2 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+2'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.3': { title: '执行抽屉第 3 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+3'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.3': { title: '直接执行第 3 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+3'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.4': { title: '执行抽屉第 4 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+4'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.4': { title: '直接执行第 4 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+4'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.5': { title: '执行抽屉第 5 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+5'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.5': { title: '直接执行第 5 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+5'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.6': { title: '执行抽屉第 6 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+6'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.6': { title: '直接执行第 6 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+6'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.7': { title: '执行抽屉第 7 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+7'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.7': { title: '直接执行第 7 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+7'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.8': { title: '执行抽屉第 8 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+8'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.8': { title: '直接执行第 8 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+8'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 },
  'ports.drawer.select.9': { title: '执行抽屉第 9 个动作', group: '端口', layer: 'port-drawer', shortcutIds: ['Ctrl+9'], when: "tab == 'ports' && portDrawerActive", weight: 400 },
  'ports.drawer.action.9': { title: '直接执行第 9 个端口动作', group: '端口', layer: 'ports', shortcutIds: ['Ctrl+Alt+9'], when: "tab == 'ports' && !portDrawerActive && !textInputFocused", weight: 130 }
} as const satisfies Record<string, ShortcutCommandProfileConfig>
